/**
 * Publisher Platform - Translations
 * Phase 12-4c: Analytics translations updated with full keys
 * 対応言語: en, ja, zh, es, fr, de, ko, ar, pt (9言語)
 */

const translations = {
    en: {
        nav: { home: 'Home', browse: 'Browse', genres: 'Genres', revenue: 'Revenue Sharing', upload: 'Upload Work', dashboard: 'Dashboard', register: 'Register', login: 'Sign In', logout: 'Logout', getStarted: 'Get Started', author: 'Author', translator: 'Translator', editor: 'Editor', notifications: 'Notifications', settings: 'Settings', support: 'Support' },
        home: { hero: { title: 'Discover Stories from Around the World', subtitle: 'Read and publish stories in 9 languages.', startReading: 'Start Reading', startWriting: 'Start Writing', availableIn: 'Available in 9 languages' }, featured: { title: 'Featured Works', viewAll: 'View All Works' }, howItWorks: { title: 'How It Works', step1: { title: 'Write & Upload', desc: 'Create your story.' }, step2: { title: 'AI Translation', desc: 'AI translates to 9 languages.' }, step3: { title: 'Earn Revenue', desc: 'Earn up to 60%.' } }, stats: { languages: 'Languages', works: 'Works', authors: 'Authors', readers: 'Readers' }, forCreators: { title: 'For Creators', desc: 'Join our community.', feature1: 'Free AI translation', feature2: 'Up to 60% revenue', feature3: 'Global reach', feature4: 'Keep your rights', button: 'Start Creating' }, revenue: { title: 'Revenue Distribution', platform: 'Platform' }, cta: { title: 'Ready to Start?', subtitle: 'Join thousands of creators.', createAccount: 'Create Free Account', browseWorks: 'Browse Works' } },
        login: { welcomeBack: 'Welcome Back', subtitle: 'Sign in to continue', email: 'Email', emailPlaceholder: 'Enter email', password: 'Password', passwordPlaceholder: 'Enter password', rememberMe: 'Remember me', forgotPassword: 'Forgot password?', signIn: 'Sign In', orContinueWith: 'or continue with', noAccount: "Don't have an account?", signUpFree: 'Sign up free' },
        register: { title: 'Create Account', subtitle: 'Join thousands worldwide', roles: { reader: 'Reader', readerDesc: 'Discover stories', author: 'Author', authorDesc: 'Write & publish', translator: 'Translator', translatorDesc: 'Translate works' }, firstName: 'First Name', firstNamePlaceholder: 'First name', lastName: 'Last Name', lastNamePlaceholder: 'Last name', createPassword: 'Create password', preferredLanguage: 'Preferred Language', agreeToTerms: 'I agree to', and: 'and', createAccount: 'Create Account', orSignUpWith: 'or sign up with', haveAccount: 'Already have account?' },
        dashboard: { title: 'Dashboard', welcome: 'Welcome back', overview: 'Overview', myWorks: 'My Works', earnings: 'Earnings', analytics: 'Analytics', recentActivity: 'Recent Activity', quickActions: 'Quick Actions', uploadNew: 'Upload New Work', viewAll: 'View All', totalRevenue: 'Total Revenue', thisMonth: 'This Month', totalViews: 'Total Views', totalWorks: 'Total Works', followers: 'Followers' },
        browse: { title: 'Browse Works', subtitle: 'Discover amazing stories', category: 'Category', allCategories: 'All Categories', language: 'Language', allLanguages: 'All Languages', sortBy: 'Sort By', mostPopular: 'Most Popular', newest: 'Newest', highestRated: 'Highest Rated', priceLowHigh: 'Price: Low to High', applyFilters: 'Apply Filters' },
        notifications: { title: 'Notification Center', subtitle: 'View notifications', settings: 'Notification Settings', all: 'All', unread: 'Unread', today: 'Today', thisWeek: 'This Week', allTypes: 'All Types', unreadOnly: 'Unread only', markAllRead: 'Mark all read', clearRead: 'Clear read', clearAll: 'Clear all' },
        analytics: { title: 'Analytics', subtitle: 'Track your performance', overview: 'Overview', views: 'Views', revenue: 'Revenue', followers: 'Followers', thisMonth: 'This Month', lastMonth: 'Last Month', growth: 'Growth', topWorks: 'Top Works', byViews: 'By Views', byRevenue: 'By Revenue', period: 'Period', days7: '7 days', days30: '30 days', days90: '90 days', lastUpdate: 'Last update', readingTime: 'Reading Time', engagement: 'Engagement', likes: 'Likes', comments: 'Comments', bookmarks: 'Bookmarks', downloads: 'Downloads', workTitle: 'Title', readers: 'Readers', noData: 'No data yet', loadFailed: 'Failed to load data', trend: 'Trend' },
        upload: { title: 'Upload Work', subtitle: 'Share your creation', dragDrop: 'Drag and drop your file here', or: 'or', browseFiles: 'Browse Files', supportedFormats: 'Supported formats', workTitle: 'Work Title', description: 'Description', category: 'Category', language: 'Language', pricing: 'Pricing', publishNow: 'Publish Now', saveDraft: 'Save as Draft' },
        checkout: { title: 'Checkout', orderSummary: 'Order Summary', subtotal: 'Subtotal', tax: 'Tax', total: 'Total', paymentMethod: 'Payment Method', creditCard: 'Credit Card', paypal: 'PayPal', completeOrder: 'Complete Order', securePayment: 'Secure Payment' },
        payment: { successTitle: 'Payment Successful', cancelTitle: 'Payment Cancelled', success: 'Payment Successful!', cancelled: 'Payment Cancelled', thankYou: 'Thank you for your purchase.', noCharge: 'No charges were made.', orderDetails: 'Order Details', orderId: 'Order ID:', item: 'Item:', amountPaid: 'Amount Paid:', date: 'Date:', supportingCreators: 'Supporting Creators:', revenueInfo: 'Your purchase supports the author (40%), translator (20%), and editor (10%).', startReading: 'Start Reading', backToHome: 'Back to Home', receiptSent: 'Receipt sent to email', possibleReasons: 'Possible reasons:', reason1: 'Back button clicked', reason2: 'Session timed out', reason3: 'Payment method issue', needHelp: 'Need Help?', contactSupport: 'Contact support', tryAgain: 'Try Again', secureInfo: 'Secure payment' },
        translation: { pageTitle: 'Translation Status', title: 'Translation Status', backToDashboard: 'Back to Dashboard', original: 'Original', totalTranslations: 'Total Translations', completed: 'Completed', inProgress: 'In Progress', overallProgress: 'Overall Progress', targetLanguage: 'Target Language', progress: 'Progress', statusCompleted: 'Completed', translating: 'Translating...', processing: 'Processing', queued: 'Queued', waiting: 'Waiting', view: 'View', aiTranslation: 'AI Translation', completed2HoursAgo: 'Completed 2 hours ago', estRemaining: 'Est. 3 min remaining', scheduledSoon: 'Scheduled soon', reviewed: 'Reviewed', professionalReview: 'Professional Review', options: 'Translation Options', addLanguages: 'Add More Languages', requestReview: 'Request Professional Review' },
        accountSettings: { title: 'Account Settings', subtitle: 'Manage your profile, security, notifications, and more', tabs: { profile: 'Profile', security: 'Security', notifications: 'Notifications', purchases: 'Purchase History', danger: 'Delete Account' }, profile: { image: 'Profile Image', changeImage: 'Change Image', imageFormats: 'JPG, PNG format, max 2MB', basicInfo: 'Basic Information', firstName: 'First Name', lastName: 'Last Name', displayName: 'Display Name (Pen Name)', displayNameHelp: 'This name will be shown to other users', bio: 'Bio', bioPlaceholder: 'Write a short bio...', preferredLang: 'Preferred Language', saveChanges: 'Save Changes' }, security: { email: 'Email Address', verified: 'Verified', notVerified: 'Not Verified', change: 'Change', backupCodes: 'Backup Codes', codesRemaining: 'codes remaining', storeSecurely: 'Store in a safe place', regenerate: 'Regenerate', securityQuestions: 'Security Questions', questionsDesc: 'Questions and answers for account recovery', changeQuestions: 'Change Questions', loginHistory: 'Login History', question: 'Question' }, notificationSettings: { emailNotifications: 'Email Notifications', workUpdates: 'Work Update Notifications', workUpdatesDesc: 'When works you follow are updated', comments: 'Comment Notifications', commentsDesc: 'When your works receive comments', sales: 'Sales Notifications', salesDesc: 'When your works are purchased', translationComplete: 'Translation Complete', translationDesc: 'When requested translations are complete', marketing: 'Marketing Emails', marketingDesc: 'News about features and campaigns', saveSettings: 'Save Settings' }, purchases: { title: 'Purchase History', desc: 'Download past purchases and receipts', loading: 'Loading...', noHistory: 'No purchase history', receipt: 'Receipt' }, danger: { title: 'Danger Zone', warning: 'The following actions cannot be undone.', deleteAccount: 'Delete Account', deleteDesc: 'All data will be permanently deleted', delete: 'Delete' }, modals: { changeEmail: 'Change Email Address', securityRequired: 'Answer security questions correctly.', newEmail: 'New Email Address', cancel: 'Cancel', deleteConfirm: 'Confirm Account Deletion', deleteWarning: 'Warning: This action cannot be undone!', deleteList1: 'Your posted works', deleteList2: 'Purchase history', deleteList3: 'Earnings and payment history', deleteList4: 'Translation requests', deleteList5: 'All account information', typeConfirm: 'Type "Delete my account" to confirm:', confirmText: 'Delete my account', permanentDelete: 'Permanently Delete', newBackupCodes: 'New Backup Codes', codesOnce: 'These codes are shown only once.', copyCode: 'Copy Codes', saved: 'Saved' }, demo: { banner: 'Demo Mode: Displaying with dummy data.', notSaved: 'Not saved in demo mode' }, loginRequired: { title: 'Login Required', message: 'Please log in to view account settings', login: 'Login' } },
        reader: { toolbar: { backToDashboard: 'Dashboard', search: 'Search', bookmarks: 'Bookmarks', addBookmark: 'Add Bookmark', settings: 'Settings', previous: 'Previous', next: 'Next' }, settings: { textSize: 'Text Size', small: 'S', medium: 'M', large: 'L', xlarge: 'XL', theme: 'Theme', light: 'Light', dark: 'Dark', sepia: 'Sepia', direction: 'Direction', horizontal: 'Horizontal', vertical: 'Vertical', rtl: 'RTL' }, search: { placeholder: 'Search...', noResults: 'No results found', foundMatches: 'Found {count} matches' }, bookmarks: { title: 'Bookmarks', noBookmarks: 'No bookmarks yet', page: 'Page' }, highlight: { yellow: 'Yellow', green: 'Green', blue: 'Blue', pink: 'Pink', remove: 'Remove', reportIssue: 'Report Translation Issue', selectText: 'Please select text to report' }, notes: { title: 'Notes', addPlaceholder: 'Add a note...', noNotes: 'No notes to export', exportTxt: 'TXT', exportWord: 'Word', exportJson: 'JSON', page: 'Page', exported: 'Exported' }, touchHint: 'Swipe left/right to turn pages', cannotHighlight: 'Cannot highlight across elements' },
        footer: { tagline: 'A multilingual publishing platform.', explore: 'Explore', authors: 'Authors', creators: 'Creators', write: 'Write', translate: 'Translate', pricing: 'Pricing', help: 'Help', faq: 'FAQ', legal: 'Legal', terms: 'Terms', privacy: 'Privacy', contact: 'Contact' },
        common: { loading: 'Loading...', save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit', submit: 'Submit', search: 'Search', filter: 'Filter', all: 'All', none: 'None', yes: 'Yes', no: 'No', back: 'Back', next: 'Next', previous: 'Previous', free: 'Free' }
    },
    ja: {
        nav: { home: 'ホーム', browse: '作品を探す', genres: 'ジャンル', revenue: '収益配分', upload: '作品アップロード', dashboard: 'ダッシュボード', register: '登録', login: 'ログイン', logout: 'ログアウト', getStarted: '今すぐ始める', author: '著者', translator: '翻訳者', editor: '編集者', notifications: '通知', settings: '設定', support: 'サポート' },
        home: { hero: { title: '世界中の物語を発見しよう', subtitle: '9言語で物語を読んで出版', startReading: '読み始める', startWriting: '書き始める', availableIn: '9言語に対応' }, featured: { title: '注目の作品', viewAll: 'すべての作品を見る' }, howItWorks: { title: '使い方', step1: { title: '書いてアップロード', desc: 'あなたの物語を作成' }, step2: { title: 'AI翻訳', desc: '9言語に即座翻訳' }, step3: { title: '収益を得る', desc: '最大60%獲得' } }, stats: { languages: '言語', works: '作品', authors: '著者', readers: '読者' }, forCreators: { title: 'クリエイターのために', desc: 'コミュニティに参加', feature1: '無料AI翻訳', feature2: '最大60%収益', feature3: 'グローバルリーチ', feature4: '権利を保持', button: '創作を始める' }, revenue: { title: '収益配分', platform: 'プラットフォーム' }, cta: { title: '始める準備はできましたか？', subtitle: 'クリエイターに参加', createAccount: '無料アカウント作成', browseWorks: '作品を探す' } },
        login: { welcomeBack: 'おかえりなさい', subtitle: 'ログインして続ける', email: 'メールアドレス', emailPlaceholder: 'メールを入力', password: 'パスワード', passwordPlaceholder: 'パスワードを入力', rememberMe: 'ログイン状態を保持', forgotPassword: 'パスワードを忘れた？', signIn: 'ログイン', orContinueWith: 'または', noAccount: 'アカウントをお持ちでない？', signUpFree: '無料で登録' },
        register: { title: 'アカウント作成', subtitle: '世界中の読者と参加', roles: { reader: '読者', readerDesc: '物語を発見', author: '著者', authorDesc: '執筆・出版', translator: '翻訳者', translatorDesc: '作品を翻訳' }, firstName: '名', firstNamePlaceholder: '名', lastName: '姓', lastNamePlaceholder: '姓', createPassword: 'パスワード作成', preferredLanguage: '優先言語', agreeToTerms: '同意します', and: 'および', createAccount: 'アカウント作成', orSignUpWith: 'または登録', haveAccount: 'アカウントをお持ち？' },
        dashboard: { title: 'ダッシュボード', welcome: 'おかえりなさい', overview: '概要', myWorks: '自分の作品', earnings: '収益', analytics: '分析', recentActivity: '最近のアクティビティ', quickActions: 'クイックアクション', uploadNew: '新しい作品をアップロード', viewAll: 'すべて見る', totalRevenue: '総収益', thisMonth: '今月', totalViews: '総閲覧数', totalWorks: '総作品数', followers: 'フォロワー' },
        browse: { title: '作品を探す', subtitle: '素晴らしい物語を発見', category: 'カテゴリ', allCategories: 'すべてのカテゴリ', language: '言語', allLanguages: 'すべての言語', sortBy: '並び替え', mostPopular: '人気順', newest: '新着順', highestRated: '評価順', priceLowHigh: '価格: 低い順', applyFilters: 'フィルターを適用' },
        notifications: { title: '通知センター', subtitle: '通知を確認', settings: '通知設定', all: '全通知', unread: '未読', today: '今日', thisWeek: '今週', allTypes: 'すべてのタイプ', unreadOnly: '未読のみ', markAllRead: 'すべて既読', clearRead: '既読を削除', clearAll: 'すべて削除' },
        analytics: { title: 'アナリティクス', subtitle: 'パフォーマンスを追跡', overview: '概要', views: '閲覧数', revenue: '収益', followers: 'フォロワー', thisMonth: '今月', lastMonth: '先月', growth: '成長率', topWorks: '人気作品', byViews: '閲覧数順', byRevenue: '収益順', period: '期間', days7: '7日間', days30: '30日間', days90: '90日間', lastUpdate: '最終更新', readingTime: '読書時間', engagement: 'エンゲージメント', likes: 'いいね', comments: 'コメント', bookmarks: 'ブックマーク', downloads: 'ダウンロード', workTitle: 'タイトル', readers: '読者数', noData: 'データがありません', loadFailed: 'データの読み込みに失敗', trend: 'トレンド' },
        upload: { title: '作品アップロード', subtitle: '作品を世界に共有', dragDrop: 'ファイルをドラッグ＆ドロップ', or: 'または', browseFiles: 'ファイルを選択', supportedFormats: '対応フォーマット', workTitle: '作品タイトル', description: '説明', category: 'カテゴリ', language: '言語', pricing: '価格設定', publishNow: '今すぐ公開', saveDraft: '下書き保存' },
        checkout: { title: 'お支払い', orderSummary: '注文内容', subtotal: '小計', tax: '税金', total: '合計', paymentMethod: '支払い方法', creditCard: 'クレジットカード', paypal: 'PayPal', completeOrder: '注文を確定', securePayment: '安全な決済' },
        payment: { successTitle: '支払い完了', cancelTitle: '支払いキャンセル', success: '支払いが完了しました！', cancelled: '支払いがキャンセルされました', thankYou: 'ご購入ありがとうございます。', noCharge: '請求はされていません。', orderDetails: '注文詳細', orderId: '注文ID:', item: '商品:', amountPaid: '支払い金額:', date: '日付:', supportingCreators: 'クリエイターをサポート:', revenueInfo: 'ご購入は著者(40%)、翻訳者(20%)、編集者(10%)を直接支援します。', startReading: '読み始める', backToHome: 'ホームに戻る', receiptSent: '領収書をメールで送信しました', possibleReasons: '以下の理由が考えられます：', reason1: '戻るボタンを押した', reason2: 'セッションがタイムアウト', reason3: '支払い方法に問題', needHelp: 'お困りですか？', contactSupport: 'サポートに連絡', tryAgain: 'もう一度試す', secureInfo: '安全な決済' },
        translation: { pageTitle: '翻訳ステータス', title: '翻訳ステータス', backToDashboard: 'ダッシュボードに戻る', original: '原文', totalTranslations: '翻訳総数', completed: '完了', inProgress: '進行中', overallProgress: '全体進捗', targetLanguage: '翻訳先言語', progress: '進捗', statusCompleted: '完了', translating: '翻訳中...', processing: '処理中', queued: '待機中', waiting: '待機中', view: '表示', aiTranslation: 'AI翻訳', completed2HoursAgo: '2時間前に完了', estRemaining: '残り約3分', scheduledSoon: 'まもなく開始', reviewed: 'レビュー済', professionalReview: 'プロレビュー', options: '翻訳オプション', addLanguages: '言語を追加', requestReview: 'プロレビューを依頼' },
        accountSettings: { title: 'アカウント設定', subtitle: 'プロフィール、セキュリティ、通知などの設定を管理', tabs: { profile: 'プロフィール', security: 'セキュリティ', notifications: '通知', purchases: '購入履歴', danger: 'アカウント削除' }, profile: { image: 'プロフィール画像', changeImage: '画像を変更', imageFormats: 'JPG, PNG形式、最大2MB', basicInfo: '基本情報', firstName: '名', lastName: '姓', displayName: '表示名（ペンネーム）', displayNameHelp: '他のユーザーに表示される名前', bio: '自己紹介', bioPlaceholder: '簡単な自己紹介...', preferredLang: '優先言語', saveChanges: '変更を保存' }, security: { email: 'メールアドレス', verified: '確認済み', notVerified: '未確認', change: '変更する', backupCodes: 'バックアップコード', codesRemaining: '個のコード', storeSecurely: '安全な場所に保管', regenerate: '再生成', securityQuestions: 'セキュリティ質問', questionsDesc: 'アカウント復旧用の質問', changeQuestions: '質問を変更', loginHistory: 'ログイン履歴', question: '質問' }, notificationSettings: { emailNotifications: 'メール通知', workUpdates: '作品の更新通知', workUpdatesDesc: 'フォロー作品が更新されたとき', comments: 'コメント通知', commentsDesc: '作品にコメントがあったとき', sales: '売上通知', salesDesc: '作品が購入されたとき', translationComplete: '翻訳完了通知', translationDesc: '翻訳が完了したとき', marketing: 'マーケティングメール', marketingDesc: '新機能やキャンペーン', saveSettings: '設定を保存' }, purchases: { title: '購入履歴', desc: '過去の購入と領収書', loading: '読み込み中...', noHistory: '購入履歴がありません', receipt: '領収書' }, danger: { title: '危険なアクション', warning: '以下の操作は取り消せません。', deleteAccount: 'アカウントを削除', deleteDesc: 'すべてのデータが削除されます', delete: '削除する' }, modals: { changeEmail: 'メールアドレスの変更', securityRequired: 'セキュリティ質問に回答してください。', newEmail: '新しいメールアドレス', cancel: 'キャンセル', deleteConfirm: '削除の確認', deleteWarning: '警告: この操作は取り消せません！', deleteList1: '投稿した作品', deleteList2: '購入履歴', deleteList3: '収益と支払い履歴', deleteList4: '翻訳依頼', deleteList5: 'すべてのアカウント情報', typeConfirm: '確認のため「アカウントを削除」と入力：', confirmText: 'アカウントを削除する', permanentDelete: '完全に削除', newBackupCodes: '新しいバックアップコード', codesOnce: 'これらのコードは一度だけ表示されます。', copyCode: 'コードをコピー', saved: '保存しました' }, demo: { banner: 'デモモード: ダミーデータで表示', notSaved: 'デモモードでは保存されません' }, loginRequired: { title: 'ログインが必要です', message: 'アカウント設定を見るにはログインしてください', login: 'ログイン' } },
        reader: { toolbar: { backToDashboard: 'ダッシュボード', search: '検索', bookmarks: 'ブックマーク', addBookmark: 'ブックマーク追加', settings: '設定', previous: '前へ', next: '次へ' }, settings: { textSize: '文字サイズ', small: '小', medium: '中', large: '大', xlarge: '特大', theme: 'テーマ', light: 'ライト', dark: 'ダーク', sepia: 'セピア', direction: '表示方向', horizontal: '横書き', vertical: '縦書き', rtl: 'RTL' }, search: { placeholder: '検索...', noResults: '結果がありません', foundMatches: '{count}件見つかりました' }, bookmarks: { title: 'ブックマーク', noBookmarks: 'ブックマークがありません', page: 'ページ' }, highlight: { yellow: '黄色', green: '緑', blue: '青', pink: 'ピンク', remove: '削除', reportIssue: '翻訳問題を報告', selectText: '報告するテキストを選択' }, notes: { title: 'メモ', addPlaceholder: 'メモを追加...', noNotes: 'エクスポートするメモがありません', exportTxt: 'TXT', exportWord: 'Word', exportJson: 'JSON', page: 'ページ', exported: 'エクスポート' }, touchHint: '左右スワイプでページ移動', cannotHighlight: '要素をまたいでハイライトできません' },
        footer: { tagline: '多言語出版プラットフォーム', explore: '探索', authors: '著者', creators: 'クリエイター', write: '執筆', translate: '翻訳', pricing: '料金', help: 'ヘルプ', faq: 'FAQ', legal: '法的情報', terms: '利用規約', privacy: 'プライバシー', contact: 'お問い合わせ' },
        common: { loading: '読み込み中...', save: '保存', cancel: 'キャンセル', delete: '削除', edit: '編集', submit: '送信', search: '検索', filter: 'フィルター', all: 'すべて', none: 'なし', yes: 'はい', no: 'いいえ', back: '戻る', next: '次へ', previous: '前へ', free: '無料' }
    },
    zh: {
        nav: { home: '首页', browse: '浏览', genres: '类型', revenue: '收益分配', upload: '上传作品', dashboard: '仪表板', register: '注册', login: '登录', logout: '退出', getStarted: '开始使用', author: '作者', translator: '翻译', editor: '编辑', notifications: '通知', settings: '设置', support: '支持' },
        home: { hero: { title: '发现世界各地的故事', subtitle: '用9种语言阅读和发布', startReading: '开始阅读', startWriting: '开始写作', availableIn: '支持9种语言' }, featured: { title: '精选作品', viewAll: '查看全部' }, howItWorks: { title: '如何使用', step1: { title: '写作和上传', desc: '创作您的故事' }, step2: { title: 'AI翻译', desc: '即时翻译' }, step3: { title: '获得收益', desc: '最高60%' } }, stats: { languages: '语言', works: '作品', authors: '作者', readers: '读者' }, forCreators: { title: '为创作者', desc: '加入社区', feature1: '免费AI翻译', feature2: '60%收益', feature3: '全球触达', feature4: '保留权利', button: '开始创作' }, revenue: { title: '收益分配', platform: '平台' }, cta: { title: '准备好了吗？', subtitle: '加入创作者', createAccount: '创建免费账户', browseWorks: '浏览作品' } },
        login: { welcomeBack: '欢迎回来', subtitle: '登录继续', email: '邮箱', emailPlaceholder: '输入邮箱', password: '密码', passwordPlaceholder: '输入密码', rememberMe: '记住我', forgotPassword: '忘记密码？', signIn: '登录', orContinueWith: '或', noAccount: '没有账户？', signUpFree: '免费注册' },
        register: { title: '创建账户', subtitle: '加入全球创作者', roles: { reader: '读者', readerDesc: '发现故事', author: '作者', authorDesc: '写作发布', translator: '译者', translatorDesc: '翻译作品' }, firstName: '名', firstNamePlaceholder: '名', lastName: '姓', lastNamePlaceholder: '姓', createPassword: '创建密码', preferredLanguage: '首选语言', agreeToTerms: '我同意', and: '和', createAccount: '创建账户', orSignUpWith: '或注册', haveAccount: '已有账户？' },
        dashboard: { title: '仪表板', welcome: '欢迎回来', overview: '概览', myWorks: '我的作品', earnings: '收益', analytics: '分析', recentActivity: '最近活动', quickActions: '快捷操作', uploadNew: '上传新作品', viewAll: '查看全部', totalRevenue: '总收入', thisMonth: '本月', totalViews: '总浏览量', totalWorks: '总作品数', followers: '粉丝' },
        browse: { title: '浏览作品', subtitle: '发现精彩故事', category: '类别', allCategories: '所有类别', language: '语言', allLanguages: '所有语言', sortBy: '排序', mostPopular: '最受欢迎', newest: '最新', highestRated: '最高评分', priceLowHigh: '价格从低到高', applyFilters: '应用筛选' },
        notifications: { title: '通知中心', subtitle: '查看通知', settings: '通知设置', all: '全部', unread: '未读', today: '今天', thisWeek: '本周', allTypes: '所有类型', unreadOnly: '仅未读', markAllRead: '全部已读', clearRead: '清除已读', clearAll: '清除全部' },
        analytics: { title: '分析', subtitle: '追踪您的表现', overview: '概览', views: '浏览量', revenue: '收益', followers: '粉丝', thisMonth: '本月', lastMonth: '上月', growth: '增长', topWorks: '热门作品', byViews: '按浏览量', byRevenue: '按收益', period: '时间段', days7: '7天', days30: '30天', days90: '90天', lastUpdate: '最后更新', readingTime: '阅读时间', engagement: '互动', likes: '点赞', comments: '评论', bookmarks: '收藏', downloads: '下载', workTitle: '标题', readers: '读者', noData: '暂无数据', loadFailed: '加载失败', trend: '趋势' },
        upload: { title: '上传作品', subtitle: '分享您的创作', dragDrop: '拖放文件到此处', or: '或', browseFiles: '浏览文件', supportedFormats: '支持的格式', workTitle: '作品标题', description: '描述', category: '类别', language: '语言', pricing: '定价', publishNow: '立即发布', saveDraft: '保存草稿' },
        checkout: { title: '结账', orderSummary: '订单摘要', subtotal: '小计', tax: '税费', total: '总计', paymentMethod: '支付方式', creditCard: '信用卡', paypal: 'PayPal', completeOrder: '完成订单', securePayment: '安全支付' },
        payment: { successTitle: '支付成功', cancelTitle: '支付取消', success: '支付成功！', cancelled: '支付已取消', thankYou: '感谢您的购买。', noCharge: '未产生任何费用。', orderDetails: '订单详情', orderId: '订单号:', item: '商品:', amountPaid: '支付金额:', date: '日期:', supportingCreators: '支持创作者:', revenueInfo: '您的购买支持作者(40%)、译者(20%)和编辑(10%)。', startReading: '开始阅读', backToHome: '返回首页', receiptSent: '收据已发送到邮箱', possibleReasons: '可能的原因：', reason1: '点击了返回按钮', reason2: '会话超时', reason3: '支付方式问题', needHelp: '需要帮助？', contactSupport: '联系支持', tryAgain: '重试', secureInfo: '安全支付' },
        translation: { pageTitle: '翻译状态', title: '翻译状态', backToDashboard: '返回仪表板', original: '原文', totalTranslations: '翻译总数', completed: '已完成', inProgress: '进行中', overallProgress: '总体进度', targetLanguage: '目标语言', progress: '进度', statusCompleted: '已完成', translating: '翻译中...', processing: '处理中', queued: '排队中', waiting: '等待中', view: '查看', aiTranslation: 'AI翻译', completed2HoursAgo: '2小时前完成', estRemaining: '预计剩余3分钟', scheduledSoon: '即将开始', reviewed: '已审核', professionalReview: '专业审核', options: '翻译选项', addLanguages: '添加更多语言', requestReview: '请求专业审核' },
        accountSettings: { title: '账户设置', subtitle: '管理您的个人资料、安全、通知等', tabs: { profile: '个人资料', security: '安全', notifications: '通知', purchases: '购买记录', danger: '删除账户' }, profile: { image: '头像', changeImage: '更换头像', imageFormats: 'JPG, PNG格式，最大2MB', basicInfo: '基本信息', firstName: '名', lastName: '姓', displayName: '显示名称（笔名）', displayNameHelp: '此名称将显示给其他用户', bio: '个人简介', bioPlaceholder: '写一段简短的自我介绍...', preferredLang: '首选语言', saveChanges: '保存更改' }, security: { email: '邮箱地址', verified: '已验证', notVerified: '未验证', change: '更改', backupCodes: '备用代码', codesRemaining: '个剩余代码', storeSecurely: '请妥善保管', regenerate: '重新生成', securityQuestions: '安全问题', questionsDesc: '用于账户恢复的问题', changeQuestions: '更改问题', loginHistory: '登录历史', question: '问题' }, notificationSettings: { emailNotifications: '邮件通知', workUpdates: '作品更新通知', workUpdatesDesc: '当关注的作品更新时', comments: '评论通知', commentsDesc: '当作品收到评论时', sales: '销售通知', salesDesc: '当作品被购买时', translationComplete: '翻译完成通知', translationDesc: '当翻译完成时', marketing: '营销邮件', marketingDesc: '功能和活动新闻', saveSettings: '保存设置' }, purchases: { title: '购买记录', desc: '下载过去的购买和收据', loading: '加载中...', noHistory: '暂无购买记录', receipt: '收据' }, danger: { title: '危险区域', warning: '以下操作无法撤销。', deleteAccount: '删除账户', deleteDesc: '所有数据将被永久删除', delete: '删除' }, modals: { changeEmail: '更改邮箱地址', securityRequired: '请正确回答安全问题。', newEmail: '新邮箱地址', cancel: '取消', deleteConfirm: '确认删除账户', deleteWarning: '警告：此操作无法撤销！', deleteList1: '您发布的作品', deleteList2: '购买记录', deleteList3: '收益和支付记录', deleteList4: '翻译请求', deleteList5: '所有账户信息', typeConfirm: '确认删除请输入"删除我的账户"：', confirmText: '删除我的账户', permanentDelete: '永久删除', newBackupCodes: '新备用代码', codesOnce: '这些代码只显示一次。', copyCode: '复制代码', saved: '已保存' }, demo: { banner: '演示模式：正在显示模拟数据。', notSaved: '演示模式下不会保存' }, loginRequired: { title: '需要登录', message: '请登录以查看账户设置', login: '登录' } },
        reader: { toolbar: { backToDashboard: '仪表板', search: '搜索', bookmarks: '书签', addBookmark: '添加书签', settings: '设置', previous: '上一页', next: '下一页' }, settings: { textSize: '字体大小', small: '小', medium: '中', large: '大', xlarge: '特大', theme: '主题', light: '浅色', dark: '深色', sepia: '护眼', direction: '方向', horizontal: '横排', vertical: '竖排', rtl: 'RTL' }, search: { placeholder: '搜索...', noResults: '未找到结果', foundMatches: '找到{count}个匹配' }, bookmarks: { title: '书签', noBookmarks: '暂无书签', page: '页' }, highlight: { yellow: '黄色', green: '绿色', blue: '蓝色', pink: '粉色', remove: '删除', reportIssue: '报告翻译问题', selectText: '请选择要报告的文本' }, notes: { title: '笔记', addPlaceholder: '添加笔记...', noNotes: '没有可导出的笔记', exportTxt: 'TXT', exportWord: 'Word', exportJson: 'JSON', page: '页', exported: '已导出' }, touchHint: '左右滑动翻页', cannotHighlight: '无法跨元素高亮' },
        footer: { tagline: '多语言出版平台', explore: '探索', authors: '作者', creators: '创作者', write: '写作', translate: '翻译', pricing: '定价', help: '帮助', faq: '常见问题', legal: '法律', terms: '条款', privacy: '隐私', contact: '联系' },
        common: { loading: '加载中...', save: '保存', cancel: '取消', delete: '删除', edit: '编辑', submit: '提交', search: '搜索', filter: '筛选', all: '全部', none: '无', yes: '是', no: '否', back: '返回', next: '下一个', previous: '上一个', free: '免费' }
    },
    es: {
        nav: { home: 'Inicio', browse: 'Explorar', genres: 'Géneros', revenue: 'Ingresos', upload: 'Subir', dashboard: 'Panel', register: 'Registrar', login: 'Entrar', logout: 'Salir', getStarted: 'Comenzar', author: 'Autor', translator: 'Traductor', editor: 'Editor', notifications: 'Notificaciones', settings: 'Configuración', support: 'Soporte' },
        analytics: { title: 'Analíticas', subtitle: 'Rastrea tu rendimiento', overview: 'Resumen', views: 'Vistas', revenue: 'Ingresos', followers: 'Seguidores', thisMonth: 'Este mes', lastMonth: 'Mes pasado', growth: 'Crecimiento', topWorks: 'Obras populares', byViews: 'Por vistas', byRevenue: 'Por ingresos', period: 'Período', days7: '7 días', days30: '30 días', days90: '90 días', lastUpdate: 'Última actualización', readingTime: 'Tiempo de lectura', engagement: 'Interacción', likes: 'Me gusta', comments: 'Comentarios', bookmarks: 'Marcadores', downloads: 'Descargas', workTitle: 'Título', readers: 'Lectores', noData: 'Sin datos', loadFailed: 'Error al cargar', trend: 'Tendencia' },
        footer: { tagline: 'Plataforma multilingüe', explore: 'Explorar', authors: 'Autores', creators: 'Creadores', write: 'Escribir', translate: 'Traducir', pricing: 'Precios', help: 'Ayuda', faq: 'FAQ', legal: 'Legal', terms: 'Términos', privacy: 'Privacidad', contact: 'Contacto' },
        common: { loading: 'Cargando...', save: 'Guardar', cancel: 'Cancelar', delete: 'Eliminar', edit: 'Editar', submit: 'Enviar', search: 'Buscar', filter: 'Filtrar', all: 'Todo', none: 'Ninguno', yes: 'Sí', no: 'No', back: 'Volver', next: 'Siguiente', previous: 'Anterior', free: 'Gratis' }
    },
    fr: {
        nav: { home: 'Accueil', browse: 'Parcourir', genres: 'Genres', revenue: 'Revenus', upload: 'Télécharger', dashboard: 'Tableau', register: "S'inscrire", login: 'Connexion', logout: 'Déconnexion', getStarted: 'Commencer', author: 'Auteur', translator: 'Traducteur', editor: 'Éditeur', notifications: 'Notifications', settings: 'Paramètres', support: 'Support' },
        analytics: { title: 'Analytiques', subtitle: 'Suivez vos performances', overview: 'Aperçu', views: 'Vues', revenue: 'Revenus', followers: 'Abonnés', thisMonth: 'Ce mois', lastMonth: 'Mois dernier', growth: 'Croissance', topWorks: 'Œuvres populaires', byViews: 'Par vues', byRevenue: 'Par revenus', period: 'Période', days7: '7 jours', days30: '30 jours', days90: '90 jours', lastUpdate: 'Dernière mise à jour', readingTime: 'Temps de lecture', engagement: 'Engagement', likes: "J'aime", comments: 'Commentaires', bookmarks: 'Favoris', downloads: 'Téléchargements', workTitle: 'Titre', readers: 'Lecteurs', noData: 'Aucune donnée', loadFailed: 'Échec du chargement', trend: 'Tendance' },
        footer: { tagline: 'Plateforme multilingue', explore: 'Explorer', authors: 'Auteurs', creators: 'Créateurs', write: 'Écrire', translate: 'Traduire', pricing: 'Tarifs', help: 'Aide', faq: 'FAQ', legal: 'Légal', terms: 'Conditions', privacy: 'Confidentialité', contact: 'Contact' },
        common: { loading: 'Chargement...', save: 'Enregistrer', cancel: 'Annuler', delete: 'Supprimer', edit: 'Modifier', submit: 'Soumettre', search: 'Rechercher', filter: 'Filtrer', all: 'Tout', none: 'Aucun', yes: 'Oui', no: 'Non', back: 'Retour', next: 'Suivant', previous: 'Précédent', free: 'Gratuit' }
    },
    de: {
        nav: { home: 'Startseite', browse: 'Durchsuchen', genres: 'Genres', revenue: 'Umsatz', upload: 'Hochladen', dashboard: 'Dashboard', register: 'Registrieren', login: 'Anmelden', logout: 'Abmelden', getStarted: 'Loslegen', author: 'Autor', translator: 'Übersetzer', editor: 'Redakteur', notifications: 'Benachrichtigungen', settings: 'Einstellungen', support: 'Support' },
        analytics: { title: 'Analysen', subtitle: 'Verfolgen Sie Ihre Leistung', overview: 'Übersicht', views: 'Aufrufe', revenue: 'Einnahmen', followers: 'Follower', thisMonth: 'Diesen Monat', lastMonth: 'Letzten Monat', growth: 'Wachstum', topWorks: 'Top-Werke', byViews: 'Nach Aufrufen', byRevenue: 'Nach Einnahmen', period: 'Zeitraum', days7: '7 Tage', days30: '30 Tage', days90: '90 Tage', lastUpdate: 'Letzte Aktualisierung', readingTime: 'Lesezeit', engagement: 'Engagement', likes: 'Gefällt mir', comments: 'Kommentare', bookmarks: 'Lesezeichen', downloads: 'Downloads', workTitle: 'Titel', readers: 'Leser', noData: 'Keine Daten', loadFailed: 'Laden fehlgeschlagen', trend: 'Trend' },
        footer: { tagline: 'Mehrsprachige Plattform', explore: 'Entdecken', authors: 'Autoren', creators: 'Kreative', write: 'Schreiben', translate: 'Übersetzen', pricing: 'Preise', help: 'Hilfe', faq: 'FAQ', legal: 'Rechtliches', terms: 'Bedingungen', privacy: 'Datenschutz', contact: 'Kontakt' },
        common: { loading: 'Laden...', save: 'Speichern', cancel: 'Abbrechen', delete: 'Löschen', edit: 'Bearbeiten', submit: 'Absenden', search: 'Suchen', filter: 'Filtern', all: 'Alle', none: 'Keine', yes: 'Ja', no: 'Nein', back: 'Zurück', next: 'Weiter', previous: 'Zurück', free: 'Kostenlos' }
    },
    ko: {
        nav: { home: '홈', browse: '둘러보기', genres: '장르', revenue: '수익', upload: '업로드', dashboard: '대시보드', register: '등록', login: '로그인', logout: '로그아웃', getStarted: '시작', author: '저자', translator: '번역가', editor: '편집자', notifications: '알림', settings: '설정', support: '지원' },
        analytics: { title: '분석', subtitle: '성과 추적', overview: '개요', views: '조회수', revenue: '수익', followers: '팔로워', thisMonth: '이번 달', lastMonth: '지난 달', growth: '성장률', topWorks: '인기 작품', byViews: '조회순', byRevenue: '수익순', period: '기간', days7: '7일', days30: '30일', days90: '90일', lastUpdate: '마지막 업데이트', readingTime: '읽은 시간', engagement: '참여', likes: '좋아요', comments: '댓글', bookmarks: '북마크', downloads: '다운로드', workTitle: '제목', readers: '독자', noData: '데이터 없음', loadFailed: '로드 실패', trend: '트렌드' },
        footer: { tagline: '다국어 플랫폼', explore: '탐색', authors: '저자', creators: '창작자', write: '쓰기', translate: '번역', pricing: '가격', help: '도움말', faq: 'FAQ', legal: '법적', terms: '약관', privacy: '개인정보', contact: '연락처' },
        common: { loading: '로딩...', save: '저장', cancel: '취소', delete: '삭제', edit: '편집', submit: '제출', search: '검색', filter: '필터', all: '전체', none: '없음', yes: '예', no: '아니오', back: '뒤로', next: '다음', previous: '이전', free: '무료' }
    },
    ar: {
        nav: { home: 'الرئيسية', browse: 'تصفح', genres: 'الأنواع', revenue: 'الإيرادات', upload: 'رفع', dashboard: 'لوحة', register: 'تسجيل', login: 'دخول', logout: 'خروج', getStarted: 'ابدأ', author: 'مؤلف', translator: 'مترجم', editor: 'محرر', notifications: 'إشعارات', settings: 'إعدادات', support: 'دعم' },
        analytics: { title: 'التحليلات', subtitle: 'تتبع أدائك', overview: 'نظرة عامة', views: 'المشاهدات', revenue: 'الإيرادات', followers: 'المتابعون', thisMonth: 'هذا الشهر', lastMonth: 'الشهر الماضي', growth: 'النمو', topWorks: 'أفضل الأعمال', byViews: 'حسب المشاهدات', byRevenue: 'حسب الإيرادات', period: 'الفترة', days7: '7 أيام', days30: '30 يوم', days90: '90 يوم', lastUpdate: 'آخر تحديث', readingTime: 'وقت القراءة', engagement: 'التفاعل', likes: 'إعجابات', comments: 'تعليقات', bookmarks: 'إشارات مرجعية', downloads: 'التحميلات', workTitle: 'العنوان', readers: 'القراء', noData: 'لا توجد بيانات', loadFailed: 'فشل التحميل', trend: 'الاتجاه' },
        footer: { tagline: 'منصة متعددة اللغات', explore: 'استكشف', authors: 'مؤلفون', creators: 'مبدعون', write: 'اكتب', translate: 'ترجم', pricing: 'أسعار', help: 'مساعدة', faq: 'أسئلة', legal: 'قانوني', terms: 'شروط', privacy: 'خصوصية', contact: 'اتصل' },
        common: { loading: 'تحميل...', save: 'حفظ', cancel: 'إلغاء', delete: 'حذف', edit: 'تعديل', submit: 'إرسال', search: 'بحث', filter: 'تصفية', all: 'الكل', none: 'لا شيء', yes: 'نعم', no: 'لا', back: 'رجوع', next: 'التالي', previous: 'السابق', free: 'مجاني' }
    },
    pt: {
        nav: { home: 'Início', browse: 'Explorar', genres: 'Gêneros', revenue: 'Receita', upload: 'Enviar', dashboard: 'Painel', register: 'Registrar', login: 'Entrar', logout: 'Sair', getStarted: 'Começar', author: 'Autor', translator: 'Tradutor', editor: 'Editor', notifications: 'Notificações', settings: 'Configurações', support: 'Suporte' },
        analytics: { title: 'Análises', subtitle: 'Acompanhe seu desempenho', overview: 'Visão geral', views: 'Visualizações', revenue: 'Receita', followers: 'Seguidores', thisMonth: 'Este mês', lastMonth: 'Mês passado', growth: 'Crescimento', topWorks: 'Obras populares', byViews: 'Por visualizações', byRevenue: 'Por receita', period: 'Período', days7: '7 dias', days30: '30 dias', days90: '90 dias', lastUpdate: 'Última atualização', readingTime: 'Tempo de leitura', engagement: 'Engajamento', likes: 'Curtidas', comments: 'Comentários', bookmarks: 'Favoritos', downloads: 'Downloads', workTitle: 'Título', readers: 'Leitores', noData: 'Sem dados', loadFailed: 'Falha ao carregar', trend: 'Tendência' },
        footer: { tagline: 'Plataforma multilíngue', explore: 'Explorar', authors: 'Autores', creators: 'Criadores', write: 'Escrever', translate: 'Traduzir', pricing: 'Preços', help: 'Ajuda', faq: 'FAQ', legal: 'Legal', terms: 'Termos', privacy: 'Privacidade', contact: 'Contato' },
        common: { loading: 'Carregando...', save: 'Salvar', cancel: 'Cancelar', delete: 'Excluir', edit: 'Editar', submit: 'Enviar', search: 'Buscar', filter: 'Filtrar', all: 'Todos', none: 'Nenhum', yes: 'Sim', no: 'Não', back: 'Voltar', next: 'Próximo', previous: 'Anterior', free: 'Grátis' }
    }
};

const availableLanguages = {
    en: { name: 'English', nativeName: 'English', flag: '🇬🇧', rtl: false },
    ja: { name: 'Japanese', nativeName: '日本語', flag: '🇯🇵', rtl: false },
    zh: { name: 'Chinese', nativeName: '中文', flag: '🇨🇳', rtl: false },
    es: { name: 'Spanish', nativeName: 'Español', flag: '🇪🇸', rtl: false },
    fr: { name: 'French', nativeName: 'Français', flag: '🇫🇷', rtl: false },
    de: { name: 'German', nativeName: 'Deutsch', flag: '🇩🇪', rtl: false },
    ko: { name: 'Korean', nativeName: '한국어', flag: '🇰🇷', rtl: false },
    ar: { name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦', rtl: true },
    pt: { name: 'Portuguese', nativeName: 'Português', flag: '🇧🇷', rtl: false }
};

function t(key, lang = null) {
    const currentLang = lang || getCurrentLanguage();
    const keys = key.split('.');
    let result = translations[currentLang];
    for (const k of keys) {
        if (result && result[k]) { result = result[k]; }
        else {
            result = translations.en;
            for (const fallbackKey of keys) {
                if (result && result[fallbackKey]) { result = result[fallbackKey]; }
                else { return key; }
            }
            break;
        }
    }
    return typeof result === 'string' ? result : key;
}

function getCurrentLanguage() {
    return localStorage.getItem('preferredLanguage') || navigator.language.split('-')[0] || 'en';
}

function setLanguage(lang) {
    if (availableLanguages[lang]) {
        localStorage.setItem('preferredLanguage', lang);
        document.documentElement.dir = availableLanguages[lang].rtl ? 'rtl' : 'ltr';
        document.documentElement.lang = lang;
        document.dispatchEvent(new CustomEvent('languageChanged', { detail: { lang } }));
    }
}

function isLanguageAvailable(lang) { return !!availableLanguages[lang]; }

window.translations = translations;
window.availableLanguages = availableLanguages;
window.t = t;
window.getCurrentLanguage = getCurrentLanguage;
window.setLanguage = setLanguage;
window.isLanguageAvailable = isLanguageAvailable;
