/**
 * Publisher Platform - Translations
 * Phase 12-2d: translation翻訳キー追加
 * 対応言語: en, ja, zh, es, fr, de, ko, ar, pt (9言語)
 */

const translations = {
    en: {
        nav: { home: 'Home', browse: 'Browse', genres: 'Genres', revenue: 'Revenue Sharing', upload: 'Upload Work', dashboard: 'Dashboard', register: 'Register', login: 'Sign In', logout: 'Logout', getStarted: 'Get Started', author: 'Author', translator: 'Translator', editor: 'Editor', notifications: 'Notifications', settings: 'Settings', support: 'Support' },
        home: { hero: { title: 'Discover Stories from Around the World', subtitle: 'Read and publish stories in 9 languages.', startReading: 'Start Reading', startWriting: 'Start Writing', availableIn: 'Available in 9 languages' }, featured: { title: 'Featured Works', viewAll: 'View All Works' }, howItWorks: { title: 'How It Works', step1: { title: 'Write & Upload', desc: 'Create your story.' }, step2: { title: 'AI Translation', desc: 'AI translates to 9 languages.' }, step3: { title: 'Earn Revenue', desc: 'Earn up to 60%.' } }, stats: { languages: 'Languages', works: 'Works', authors: 'Authors', readers: 'Readers' }, forCreators: { title: 'For Creators', desc: 'Join our community.', feature1: 'Free AI translation', feature2: 'Up to 60% revenue', feature3: 'Global reach', feature4: 'Keep your rights', button: 'Start Creating' }, revenue: { title: 'Revenue Distribution', platform: 'Platform' }, cta: { title: 'Ready to Start?', subtitle: 'Join thousands of creators.', createAccount: 'Create Free Account', browseWorks: 'Browse Works' } },
        login: { welcomeBack: 'Welcome Back', subtitle: 'Sign in to continue', email: 'Email', emailPlaceholder: 'Enter email', password: 'Password', passwordPlaceholder: 'Enter password', rememberMe: 'Remember me', forgotPassword: 'Forgot password?', signIn: 'Sign In', orContinueWith: 'or continue with', noAccount: "Don't have an account?", signUpFree: 'Sign up free' },
        register: { title: 'Create Account', subtitle: 'Join thousands worldwide', roles: { reader: 'Reader', readerDesc: 'Discover stories', author: 'Author', authorDesc: 'Write & publish', translator: 'Translator', translatorDesc: 'Translate works' }, firstName: 'First Name', firstNamePlaceholder: 'First name', lastName: 'Last Name', lastNamePlaceholder: 'Last name', createPassword: 'Create password', preferredLanguage: 'Preferred Language', agreeToTerms: 'I agree to', and: 'and', createAccount: 'Create Account', orSignUpWith: 'or sign up with', haveAccount: 'Already have account?' },
        dashboard: { title: 'Dashboard', welcome: 'Welcome back', overview: 'Overview', myWorks: 'My Works', earnings: 'Earnings', analytics: 'Analytics', recentActivity: 'Recent Activity', quickActions: 'Quick Actions', uploadNew: 'Upload New Work', viewAll: 'View All', totalRevenue: 'Total Revenue', thisMonth: 'This Month', totalViews: 'Total Views', totalWorks: 'Total Works', followers: 'Followers' },
        browse: { title: 'Browse Works', subtitle: 'Discover amazing stories', category: 'Category', allCategories: 'All Categories', language: 'Language', allLanguages: 'All Languages', sortBy: 'Sort By', mostPopular: 'Most Popular', newest: 'Newest', highestRated: 'Highest Rated', priceLowHigh: 'Price: Low to High', applyFilters: 'Apply Filters' },
        notifications: { title: 'Notification Center', subtitle: 'View notifications', settings: 'Notification Settings', all: 'All', unread: 'Unread', today: 'Today', thisWeek: 'This Week', allTypes: 'All Types', unreadOnly: 'Unread only', markAllRead: 'Mark all read', clearRead: 'Clear read', clearAll: 'Clear all' },
        analytics: { title: 'Analytics', subtitle: 'Track your performance', overview: 'Overview', views: 'Views', revenue: 'Revenue', followers: 'Followers', thisMonth: 'This Month', lastMonth: 'Last Month', growth: 'Growth', topWorks: 'Top Works', byViews: 'By Views', byRevenue: 'By Revenue' },
        upload: { title: 'Upload Work', subtitle: 'Share your creation', dragDrop: 'Drag and drop your file here', or: 'or', browseFiles: 'Browse Files', supportedFormats: 'Supported formats', workTitle: 'Work Title', description: 'Description', category: 'Category', language: 'Language', pricing: 'Pricing', publishNow: 'Publish Now', saveDraft: 'Save as Draft' },
        checkout: { title: 'Checkout', orderSummary: 'Order Summary', subtotal: 'Subtotal', tax: 'Tax', total: 'Total', paymentMethod: 'Payment Method', creditCard: 'Credit Card', paypal: 'PayPal', completeOrder: 'Complete Order', securePayment: 'Secure Payment' },
        payment: { successTitle: 'Payment Successful', cancelTitle: 'Payment Cancelled', success: 'Payment Successful!', cancelled: 'Payment Cancelled', thankYou: 'Thank you for your purchase. Your content is now available.', noCharge: 'Your payment was not completed. No charges were made.', orderDetails: 'Order Details', orderId: 'Order ID:', item: 'Item:', amountPaid: 'Amount Paid:', date: 'Date:', supportingCreators: 'Supporting Creators:', revenueInfo: 'Your purchase supports the author (40%), translator (20%), and editor (10%).', startReading: 'Start Reading', backToHome: 'Back to Home', receiptSent: 'A receipt has been sent to your email', possibleReasons: 'This might have happened because:', reason1: 'You clicked the back button or closed the payment window', reason2: 'The payment session timed out', reason3: 'There was an issue with your payment method', needHelp: 'Need Help?', contactSupport: 'Please contact our support team at', tryAgain: 'Try Again', secureInfo: 'Your payment information is always secure' },
        translation: { pageTitle: 'Translation Status', title: 'Translation Status', backToDashboard: 'Back to Dashboard', original: 'Original', totalTranslations: 'Total Translations', completed: 'Completed', inProgress: 'In Progress', overallProgress: 'Overall Progress', targetLanguage: 'Target Language', progress: 'Progress', statusCompleted: 'Completed', translating: 'Translating...', processing: 'Processing', queued: 'Queued', waiting: 'Waiting', view: 'View', aiTranslation: 'AI Translation', completed2HoursAgo: 'Completed 2 hours ago', estRemaining: 'Est. 3 min remaining', scheduledSoon: 'Scheduled soon', reviewed: 'Reviewed', professionalReview: 'Professional Review', options: 'Translation Options', addLanguages: 'Add More Languages', requestReview: 'Request Professional Review' },
        footer: { tagline: 'A multilingual publishing platform.', explore: 'Explore', authors: 'Authors', creators: 'Creators', write: 'Write', translate: 'Translate', pricing: 'Pricing', help: 'Help', faq: 'FAQ', legal: 'Legal', terms: 'Terms', privacy: 'Privacy', contact: 'Contact' },
        common: { loading: 'Loading...', save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit', submit: 'Submit', search: 'Search', filter: 'Filter', all: 'All', none: 'None', yes: 'Yes', no: 'No', back: 'Back', next: 'Next', previous: 'Previous', free: 'Free' }
    },
    ja: {
        nav: { home: 'ホーム', browse: '作品を探す', genres: 'ジャンル', revenue: '収益配分', upload: '作品アップロード', dashboard: 'ダッシュボード', register: '登録', login: 'ログイン', logout: 'ログアウト', getStarted: '今すぐ始める', author: '著者', translator: '翻訳者', editor: '編集者', notifications: '通知', settings: '設定', support: 'サポート' },
        home: { hero: { title: '世界中の物語を発見しよう', subtitle: '9言語で物語を読んで出版', startReading: '読み始める', startWriting: '書き始める', availableIn: '9言語に対応' }, featured: { title: '注目の作品', viewAll: 'すべての作品を見る' }, howItWorks: { title: '使い方', step1: { title: '書いてアップロード', desc: 'あなたの物語を作成' }, step2: { title: 'AI翻訳', desc: '9言語に即座翻訳' }, step3: { title: '収益を得る', desc: '最大60%獲得' } }, stats: { languages: '言語', works: '作品', authors: '著者', readers: '読者' }, forCreators: { title: 'クリエイターのために', desc: 'コミュニティに参加', feature1: '無料AI翻訳', feature2: '最大60%収益', feature3: 'グローバルリーチ', feature4: '権利を保持', button: '創作を始める' }, revenue: { title: '収益配分', platform: 'プラットフォーム' }, cta: { title: '始める準備はできましたか？', subtitle: 'クリエイターに参加', createAccount: '無料アカウント作成', browseWorks: '作品を探す' } },
        login: { welcomeBack: 'おかえりなさい', subtitle: 'ログインして続ける', email: 'メールアドレス', emailPlaceholder: 'メールを入力', password: 'パスワード', passwordPlaceholder: 'パスワードを入力', rememberMe: 'ログイン状態を保持', forgotPassword: 'パスワードを忘れた？', signIn: 'ログイン', orContinueWith: 'または', noAccount: 'アカウントをお持ちでない？', signUpFree: '無料で登録' },
        register: { title: 'アカウント作成', subtitle: '世界中の読者と参加', roles: { reader: '読者', readerDesc: '物語を発見', author: '著者', authorDesc: '執筆・出版', translator: '翻訳者', translatorDesc: '作品を翻訳' }, firstName: '名', firstNamePlaceholder: '名', lastName: '姓', lastNamePlaceholder: '姓', createPassword: 'パスワード作成', preferredLanguage: '優先言語', agreeToTerms: '同意します', and: 'および', createAccount: 'アカウント作成', orSignUpWith: 'または登録', haveAccount: 'アカウントをお持ち？' },
        dashboard: { title: 'ダッシュボード', welcome: 'おかえりなさい', overview: '概要', myWorks: '自分の作品', earnings: '収益', analytics: '分析', recentActivity: '最近のアクティビティ', quickActions: 'クイックアクション', uploadNew: '新しい作品をアップロード', viewAll: 'すべて見る', totalRevenue: '総収益', thisMonth: '今月', totalViews: '総閲覧数', totalWorks: '総作品数', followers: 'フォロワー' },
        browse: { title: '作品を探す', subtitle: '素晴らしい物語を発見', category: 'カテゴリ', allCategories: 'すべてのカテゴリ', language: '言語', allLanguages: 'すべての言語', sortBy: '並び替え', mostPopular: '人気順', newest: '新着順', highestRated: '評価順', priceLowHigh: '価格: 低い順', applyFilters: 'フィルターを適用' },
        notifications: { title: '通知センター', subtitle: '通知を確認', settings: '通知設定', all: '全通知', unread: '未読', today: '今日', thisWeek: '今週', allTypes: 'すべてのタイプ', unreadOnly: '未読のみ', markAllRead: 'すべて既読', clearRead: '既読を削除', clearAll: 'すべて削除' },
        analytics: { title: '分析', subtitle: 'パフォーマンスを追跡', overview: '概要', views: '閲覧数', revenue: '収益', followers: 'フォロワー', thisMonth: '今月', lastMonth: '先月', growth: '成長率', topWorks: '人気作品', byViews: '閲覧数順', byRevenue: '収益順' },
        upload: { title: '作品アップロード', subtitle: '作品を世界に共有', dragDrop: 'ファイルをドラッグ＆ドロップ', or: 'または', browseFiles: 'ファイルを選択', supportedFormats: '対応フォーマット', workTitle: '作品タイトル', description: '説明', category: 'カテゴリ', language: '言語', pricing: '価格設定', publishNow: '今すぐ公開', saveDraft: '下書き保存' },
        checkout: { title: 'お支払い', orderSummary: '注文内容', subtotal: '小計', tax: '税金', total: '合計', paymentMethod: '支払い方法', creditCard: 'クレジットカード', paypal: 'PayPal', completeOrder: '注文を確定', securePayment: '安全な決済' },
        payment: { successTitle: '支払い完了', cancelTitle: '支払いキャンセル', success: '支払いが完了しました！', cancelled: '支払いがキャンセルされました', thankYou: 'ご購入ありがとうございます。コンテンツをご利用いただけます。', noCharge: '支払いは完了していません。請求はされていません。', orderDetails: '注文詳細', orderId: '注文ID:', item: '商品:', amountPaid: '支払い金額:', date: '日付:', supportingCreators: 'クリエイターをサポート:', revenueInfo: 'ご購入は著者(40%)、翻訳者(20%)、編集者(10%)を直接支援します。', startReading: '読み始める', backToHome: 'ホームに戻る', receiptSent: '領収書をメールで送信しました', possibleReasons: '以下の理由が考えられます：', reason1: '戻るボタンを押したか支払い画面を閉じた', reason2: '支払いセッションがタイムアウトした', reason3: '支払い方法に問題があった', needHelp: 'お困りですか？', contactSupport: 'サポートチームにお問い合わせください', tryAgain: 'もう一度試す', secureInfo: 'お支払い情報は常に安全です' },
        translation: { pageTitle: '翻訳ステータス', title: '翻訳ステータス', backToDashboard: 'ダッシュボードに戻る', original: '原文', totalTranslations: '翻訳総数', completed: '完了', inProgress: '進行中', overallProgress: '全体進捗', targetLanguage: '翻訳先言語', progress: '進捗', statusCompleted: '完了', translating: '翻訳中...', processing: '処理中', queued: '待機中', waiting: '待機中', view: '表示', aiTranslation: 'AI翻訳', completed2HoursAgo: '2時間前に完了', estRemaining: '残り約3分', scheduledSoon: 'まもなく開始', reviewed: 'レビュー済', professionalReview: 'プロレビュー', options: '翻訳オプション', addLanguages: '言語を追加', requestReview: 'プロレビューを依頼' },
        footer: { tagline: '多言語出版プラットフォーム', explore: '探索', authors: '著者', creators: 'クリエイター', write: '執筆', translate: '翻訳', pricing: '料金', help: 'ヘルプ', faq: 'FAQ', legal: '法的情報', terms: '利用規約', privacy: 'プライバシー', contact: 'お問い合わせ' },
        common: { loading: '読み込み中...', save: '保存', cancel: 'キャンセル', delete: '削除', edit: '編集', submit: '送信', search: '検索', filter: 'フィルター', all: 'すべて', none: 'なし', yes: 'はい', no: 'いいえ', back: '戻る', next: '次へ', previous: '前へ', free: '無料' }
    },
    zh: {
        nav: { home: '首页', browse: '浏览', genres: '类型', revenue: '收益分配', upload: '上传作品', dashboard: '仪表板', register: '注册', login: '登录', logout: '退出', getStarted: '开始使用', author: '作者', translator: '翻译', editor: '编辑', notifications: '通知', settings: '设置', support: '支持' },
        home: { hero: { title: '发现来自世界各地的故事', subtitle: '用9种语言阅读和发布', startReading: '开始阅读', startWriting: '开始写作', availableIn: '支持9种语言' }, featured: { title: '精选作品', viewAll: '查看全部' }, howItWorks: { title: '如何使用', step1: { title: '写作和上传', desc: '创作您的故事' }, step2: { title: 'AI翻译', desc: '即时翻译' }, step3: { title: '获得收益', desc: '最高60%' } }, stats: { languages: '语言', works: '作品', authors: '作者', readers: '读者' }, forCreators: { title: '为创作者', desc: '加入社区', feature1: '免费AI翻译', feature2: '60%收益', feature3: '全球触达', feature4: '保留权利', button: '开始创作' }, revenue: { title: '收益分配', platform: '平台' }, cta: { title: '准备好了吗？', subtitle: '加入创作者', createAccount: '创建免费账户', browseWorks: '浏览作品' } },
        login: { welcomeBack: '欢迎回来', subtitle: '登录继续', email: '邮箱', emailPlaceholder: '输入邮箱', password: '密码', passwordPlaceholder: '输入密码', rememberMe: '记住我', forgotPassword: '忘记密码？', signIn: '登录', orContinueWith: '或', noAccount: '没有账户？', signUpFree: '免费注册' },
        register: { title: '创建账户', subtitle: '加入全球创作者', roles: { reader: '读者', readerDesc: '发现故事', author: '作者', authorDesc: '写作发布', translator: '译者', translatorDesc: '翻译作品' }, firstName: '名', firstNamePlaceholder: '名', lastName: '姓', lastNamePlaceholder: '姓', createPassword: '创建密码', preferredLanguage: '首选语言', agreeToTerms: '我同意', and: '和', createAccount: '创建账户', orSignUpWith: '或注册', haveAccount: '已有账户？' },
        dashboard: { title: '仪表板', welcome: '欢迎回来', overview: '概览', myWorks: '我的作品', earnings: '收益', analytics: '分析', recentActivity: '最近活动', quickActions: '快捷操作', uploadNew: '上传新作品', viewAll: '查看全部', totalRevenue: '总收入', thisMonth: '本月', totalViews: '总浏览量', totalWorks: '总作品数', followers: '粉丝' },
        browse: { title: '浏览作品', subtitle: '发现精彩故事', category: '类别', allCategories: '所有类别', language: '语言', allLanguages: '所有语言', sortBy: '排序', mostPopular: '最受欢迎', newest: '最新', highestRated: '最高评分', priceLowHigh: '价格: 从低到高', applyFilters: '应用筛选' },
        notifications: { title: '通知中心', subtitle: '查看通知', settings: '通知设置', all: '全部', unread: '未读', today: '今天', thisWeek: '本周', allTypes: '所有类型', unreadOnly: '仅未读', markAllRead: '全部已读', clearRead: '清除已读', clearAll: '清除全部' },
        analytics: { title: '分析', subtitle: '追踪表现', overview: '概览', views: '浏览量', revenue: '收入', followers: '粉丝', thisMonth: '本月', lastMonth: '上月', growth: '增长', topWorks: '热门作品', byViews: '按浏览量', byRevenue: '按收入' },
        upload: { title: '上传作品', subtitle: '分享您的创作', dragDrop: '拖放文件到此处', or: '或', browseFiles: '浏览文件', supportedFormats: '支持的格式', workTitle: '作品标题', description: '描述', category: '类别', language: '语言', pricing: '定价', publishNow: '立即发布', saveDraft: '保存草稿' },
        checkout: { title: '结账', orderSummary: '订单摘要', subtotal: '小计', tax: '税费', total: '总计', paymentMethod: '支付方式', creditCard: '信用卡', paypal: 'PayPal', completeOrder: '完成订单', securePayment: '安全支付' },
        payment: { successTitle: '支付成功', cancelTitle: '支付取消', success: '支付成功！', cancelled: '支付已取消', thankYou: '感谢您的购买。您的内容现已可用。', noCharge: '支付未完成。未产生任何费用。', orderDetails: '订单详情', orderId: '订单号:', item: '商品:', amountPaid: '支付金额:', date: '日期:', supportingCreators: '支持创作者:', revenueInfo: '您的购买直接支持作者(40%)、译者(20%)和编辑(10%)。', startReading: '开始阅读', backToHome: '返回首页', receiptSent: '收据已发送到您的邮箱', possibleReasons: '可能的原因：', reason1: '您点击了返回按钮或关闭了支付窗口', reason2: '支付会话超时', reason3: '支付方式存在问题', needHelp: '需要帮助？', contactSupport: '请联系我们的支持团队', tryAgain: '重试', secureInfo: '您的支付信息始终是安全的' },
        translation: { pageTitle: '翻译状态', title: '翻译状态', backToDashboard: '返回仪表板', original: '原文', totalTranslations: '翻译总数', completed: '已完成', inProgress: '进行中', overallProgress: '总体进度', targetLanguage: '目标语言', progress: '进度', statusCompleted: '已完成', translating: '翻译中...', processing: '处理中', queued: '排队中', waiting: '等待中', view: '查看', aiTranslation: 'AI翻译', completed2HoursAgo: '2小时前完成', estRemaining: '预计剩余3分钟', scheduledSoon: '即将开始', reviewed: '已审核', professionalReview: '专业审核', options: '翻译选项', addLanguages: '添加更多语言', requestReview: '请求专业审核' },
        footer: { tagline: '多语言出版平台', explore: '探索', authors: '作者', creators: '创作者', write: '写作', translate: '翻译', pricing: '定价', help: '帮助', faq: '常见问题', legal: '法律', terms: '条款', privacy: '隐私', contact: '联系' },
        common: { loading: '加载中...', save: '保存', cancel: '取消', delete: '删除', edit: '编辑', submit: '提交', search: '搜索', filter: '筛选', all: '全部', none: '无', yes: '是', no: '否', back: '返回', next: '下一个', previous: '上一个', free: '免费' }
    },
    es: {
        nav: { home: 'Inicio', browse: 'Explorar', genres: 'Géneros', revenue: 'Ingresos', upload: 'Subir', dashboard: 'Panel', register: 'Registrar', login: 'Entrar', logout: 'Salir', getStarted: 'Comenzar', author: 'Autor', translator: 'Traductor', editor: 'Editor', notifications: 'Notificaciones', settings: 'Configuración', support: 'Soporte' },
        home: { hero: { title: 'Descubre Historias del Mundo', subtitle: 'Lee y publica en 9 idiomas', startReading: 'Leer', startWriting: 'Escribir', availableIn: '9 idiomas' }, featured: { title: 'Destacadas', viewAll: 'Ver Todo' }, howItWorks: { title: 'Cómo Funciona', step1: { title: 'Escribe', desc: 'Crea tu historia' }, step2: { title: 'IA', desc: 'Traducción' }, step3: { title: 'Gana', desc: '60%' } }, stats: { languages: 'Idiomas', works: 'Obras', authors: 'Autores', readers: 'Lectores' }, forCreators: { title: 'Creadores', desc: 'Únete', feature1: 'IA gratis', feature2: '60%', feature3: 'Global', feature4: 'Derechos', button: 'Crear' }, revenue: { title: 'Distribución', platform: 'Plataforma' }, cta: { title: '¿Listo?', subtitle: 'Únete', createAccount: 'Cuenta Gratis', browseWorks: 'Explorar' } },
        login: { welcomeBack: 'Bienvenido', subtitle: 'Inicia sesión', email: 'Email', emailPlaceholder: 'Tu email', password: 'Contraseña', passwordPlaceholder: 'Tu contraseña', rememberMe: 'Recordar', forgotPassword: '¿Olvidaste?', signIn: 'Entrar', orContinueWith: 'o', noAccount: '¿Sin cuenta?', signUpFree: 'Regístrate' },
        register: { title: 'Crear Cuenta', subtitle: 'Únete', roles: { reader: 'Lector', readerDesc: 'Descubre', author: 'Autor', authorDesc: 'Escribe', translator: 'Traductor', translatorDesc: 'Traduce' }, firstName: 'Nombre', firstNamePlaceholder: 'Nombre', lastName: 'Apellido', lastNamePlaceholder: 'Apellido', createPassword: 'Contraseña', preferredLanguage: 'Idioma', agreeToTerms: 'Acepto', and: 'y', createAccount: 'Crear', orSignUpWith: 'o', haveAccount: '¿Ya tienes?' },
        dashboard: { title: 'Panel', welcome: 'Bienvenido', overview: 'Resumen', myWorks: 'Mis Obras', earnings: 'Ganancias', analytics: 'Análisis', recentActivity: 'Actividad', quickActions: 'Acciones', uploadNew: 'Subir', viewAll: 'Ver Todo', totalRevenue: 'Ingresos', thisMonth: 'Este Mes', totalViews: 'Vistas', totalWorks: 'Obras', followers: 'Seguidores' },
        browse: { title: 'Explorar', subtitle: 'Descubre historias', category: 'Categoría', allCategories: 'Todas', language: 'Idioma', allLanguages: 'Todos', sortBy: 'Ordenar', mostPopular: 'Popular', newest: 'Nuevo', highestRated: 'Valorado', priceLowHigh: 'Precio', applyFilters: 'Aplicar' },
        notifications: { title: 'Notificaciones', subtitle: 'Ver', settings: 'Configuración', all: 'Todo', unread: 'No Leído', today: 'Hoy', thisWeek: 'Semana', allTypes: 'Todos', unreadOnly: 'No Leídos', markAllRead: 'Marcar', clearRead: 'Limpiar', clearAll: 'Todo' },
        analytics: { title: 'Análisis', subtitle: 'Rendimiento', overview: 'Resumen', views: 'Vistas', revenue: 'Ingresos', followers: 'Seguidores', thisMonth: 'Este Mes', lastMonth: 'Pasado', growth: 'Crecimiento', topWorks: 'Top', byViews: 'Vistas', byRevenue: 'Ingresos' },
        upload: { title: 'Subir', subtitle: 'Comparte', dragDrop: 'Arrastra', or: 'o', browseFiles: 'Buscar', supportedFormats: 'Formatos', workTitle: 'Título', description: 'Descripción', category: 'Categoría', language: 'Idioma', pricing: 'Precio', publishNow: 'Publicar', saveDraft: 'Guardar' },
        checkout: { title: 'Pago', orderSummary: 'Resumen', subtotal: 'Subtotal', tax: 'Impuesto', total: 'Total', paymentMethod: 'Método', creditCard: 'Tarjeta', paypal: 'PayPal', completeOrder: 'Completar', securePayment: 'Seguro' },
        payment: { successTitle: 'Pago Exitoso', cancelTitle: 'Pago Cancelado', success: '¡Pago Exitoso!', cancelled: 'Pago Cancelado', thankYou: 'Gracias por tu compra. Tu contenido está disponible.', noCharge: 'Tu pago no se completó. No se realizaron cargos.', orderDetails: 'Detalles del Pedido', orderId: 'ID de Pedido:', item: 'Artículo:', amountPaid: 'Monto Pagado:', date: 'Fecha:', supportingCreators: 'Apoyando Creadores:', revenueInfo: 'Tu compra apoya al autor (40%), traductor (20%) y editor (10%).', startReading: 'Comenzar a Leer', backToHome: 'Volver al Inicio', receiptSent: 'Se ha enviado un recibo a tu email', possibleReasons: 'Esto pudo haber pasado porque:', reason1: 'Hiciste clic en el botón de retroceso', reason2: 'La sesión de pago expiró', reason3: 'Hubo un problema con tu método de pago', needHelp: '¿Necesitas Ayuda?', contactSupport: 'Contacta a nuestro equipo de soporte', tryAgain: 'Intentar de Nuevo', secureInfo: 'Tu información de pago siempre está segura' },
        translation: { pageTitle: 'Estado de Traducción', title: 'Estado de Traducción', backToDashboard: 'Volver al Panel', original: 'Original', totalTranslations: 'Traducciones', completed: 'Completadas', inProgress: 'En Progreso', overallProgress: 'Progreso Total', targetLanguage: 'Idioma Destino', progress: 'Progreso', statusCompleted: 'Completado', translating: 'Traduciendo...', processing: 'Procesando', queued: 'En Cola', waiting: 'Esperando', view: 'Ver', aiTranslation: 'Traducción IA', completed2HoursAgo: 'Completado hace 2h', estRemaining: 'Est. 3 min restantes', scheduledSoon: 'Pronto', reviewed: 'Revisado', professionalReview: 'Revisión Profesional', options: 'Opciones de Traducción', addLanguages: 'Agregar Idiomas', requestReview: 'Solicitar Revisión' },
        footer: { tagline: 'Plataforma multilingüe', explore: 'Explorar', authors: 'Autores', creators: 'Creadores', write: 'Escribir', translate: 'Traducir', pricing: 'Precios', help: 'Ayuda', faq: 'FAQ', legal: 'Legal', terms: 'Términos', privacy: 'Privacidad', contact: 'Contacto' },
        common: { loading: 'Cargando...', save: 'Guardar', cancel: 'Cancelar', delete: 'Eliminar', edit: 'Editar', submit: 'Enviar', search: 'Buscar', filter: 'Filtrar', all: 'Todo', none: 'Ninguno', yes: 'Sí', no: 'No', back: 'Volver', next: 'Siguiente', previous: 'Anterior', free: 'Gratis' }
    },
    fr: {
        nav: { home: 'Accueil', browse: 'Parcourir', genres: 'Genres', revenue: 'Revenus', upload: 'Télécharger', dashboard: 'Tableau', register: "S'inscrire", login: 'Connexion', logout: 'Déconnexion', getStarted: 'Commencer', author: 'Auteur', translator: 'Traducteur', editor: 'Éditeur', notifications: 'Notifications', settings: 'Paramètres', support: 'Support' },
        home: { hero: { title: 'Découvrez des Histoires', subtitle: '9 langues', startReading: 'Lire', startWriting: 'Écrire', availableIn: '9 langues' }, featured: { title: 'Vedette', viewAll: 'Tout' }, howItWorks: { title: 'Comment', step1: { title: 'Écrivez', desc: 'Histoire' }, step2: { title: 'IA', desc: 'Traduction' }, step3: { title: 'Gagnez', desc: '60%' } }, stats: { languages: 'Langues', works: 'Œuvres', authors: 'Auteurs', readers: 'Lecteurs' }, forCreators: { title: 'Créateurs', desc: 'Rejoignez', feature1: 'IA gratuite', feature2: '60%', feature3: 'Mondial', feature4: 'Droits', button: 'Créer' }, revenue: { title: 'Distribution', platform: 'Plateforme' }, cta: { title: 'Prêt?', subtitle: 'Rejoignez', createAccount: 'Compte', browseWorks: 'Parcourir' } },
        login: { welcomeBack: 'Bon Retour', subtitle: 'Connexion', email: 'Email', emailPlaceholder: 'Email', password: 'Mot de passe', passwordPlaceholder: 'Mot de passe', rememberMe: 'Souvenir', forgotPassword: 'Oublié?', signIn: 'Connexion', orContinueWith: 'ou', noAccount: 'Pas de compte?', signUpFree: 'Inscrivez-vous' },
        register: { title: 'Créer Compte', subtitle: 'Rejoignez', roles: { reader: 'Lecteur', readerDesc: 'Découvrez', author: 'Auteur', authorDesc: 'Écrivez', translator: 'Traducteur', translatorDesc: 'Traduisez' }, firstName: 'Prénom', firstNamePlaceholder: 'Prénom', lastName: 'Nom', lastNamePlaceholder: 'Nom', createPassword: 'Mot de passe', preferredLanguage: 'Langue', agreeToTerms: "J'accepte", and: 'et', createAccount: 'Créer', orSignUpWith: 'ou', haveAccount: 'Déjà inscrit?' },
        dashboard: { title: 'Tableau', welcome: 'Bienvenue', overview: 'Aperçu', myWorks: 'Œuvres', earnings: 'Revenus', analytics: 'Analyses', recentActivity: 'Activité', quickActions: 'Actions', uploadNew: 'Télécharger', viewAll: 'Tout', totalRevenue: 'Revenus', thisMonth: 'Ce Mois', totalViews: 'Vues', totalWorks: 'Œuvres', followers: 'Abonnés' },
        browse: { title: 'Parcourir', subtitle: 'Découvrez', category: 'Catégorie', allCategories: 'Toutes', language: 'Langue', allLanguages: 'Toutes', sortBy: 'Trier', mostPopular: 'Populaire', newest: 'Récent', highestRated: 'Noté', priceLowHigh: 'Prix', applyFilters: 'Appliquer' },
        notifications: { title: 'Notifications', subtitle: 'Voir', settings: 'Paramètres', all: 'Tout', unread: 'Non Lu', today: "Aujourd'hui", thisWeek: 'Semaine', allTypes: 'Tous', unreadOnly: 'Non Lus', markAllRead: 'Marquer', clearRead: 'Effacer', clearAll: 'Tout' },
        analytics: { title: 'Analyses', subtitle: 'Performance', overview: 'Aperçu', views: 'Vues', revenue: 'Revenus', followers: 'Abonnés', thisMonth: 'Ce Mois', lastMonth: 'Dernier', growth: 'Croissance', topWorks: 'Top', byViews: 'Vues', byRevenue: 'Revenus' },
        upload: { title: 'Télécharger', subtitle: 'Partagez', dragDrop: 'Glissez', or: 'ou', browseFiles: 'Parcourir', supportedFormats: 'Formats', workTitle: 'Titre', description: 'Description', category: 'Catégorie', language: 'Langue', pricing: 'Prix', publishNow: 'Publier', saveDraft: 'Brouillon' },
        checkout: { title: 'Paiement', orderSummary: 'Résumé', subtotal: 'Sous-total', tax: 'Taxe', total: 'Total', paymentMethod: 'Méthode', creditCard: 'Carte', paypal: 'PayPal', completeOrder: 'Finaliser', securePayment: 'Sécurisé' },
        payment: { successTitle: 'Paiement Réussi', cancelTitle: 'Paiement Annulé', success: 'Paiement Réussi!', cancelled: 'Paiement Annulé', thankYou: 'Merci pour votre achat. Votre contenu est disponible.', noCharge: 'Votre paiement n\'a pas été complété. Aucun frais.', orderDetails: 'Détails de la Commande', orderId: 'ID Commande:', item: 'Article:', amountPaid: 'Montant Payé:', date: 'Date:', supportingCreators: 'Soutenir les Créateurs:', revenueInfo: 'Votre achat soutient l\'auteur (40%), traducteur (20%) et éditeur (10%).', startReading: 'Commencer à Lire', backToHome: 'Retour à l\'Accueil', receiptSent: 'Un reçu a été envoyé à votre email', possibleReasons: 'Cela peut être dû à:', reason1: 'Vous avez cliqué sur le bouton retour', reason2: 'La session de paiement a expiré', reason3: 'Il y avait un problème avec votre méthode de paiement', needHelp: 'Besoin d\'Aide?', contactSupport: 'Contactez notre équipe de support', tryAgain: 'Réessayer', secureInfo: 'Vos informations de paiement sont toujours sécurisées' },
        translation: { pageTitle: 'État de Traduction', title: 'État de Traduction', backToDashboard: 'Retour au Tableau', original: 'Original', totalTranslations: 'Traductions', completed: 'Terminées', inProgress: 'En Cours', overallProgress: 'Progrès Global', targetLanguage: 'Langue Cible', progress: 'Progrès', statusCompleted: 'Terminé', translating: 'Traduction...', processing: 'Traitement', queued: 'En File', waiting: 'En Attente', view: 'Voir', aiTranslation: 'Traduction IA', completed2HoursAgo: 'Terminé il y a 2h', estRemaining: 'Est. 3 min restantes', scheduledSoon: 'Bientôt', reviewed: 'Révisé', professionalReview: 'Révision Pro', options: 'Options de Traduction', addLanguages: 'Ajouter des Langues', requestReview: 'Demander Révision' },
        footer: { tagline: 'Plateforme multilingue', explore: 'Explorer', authors: 'Auteurs', creators: 'Créateurs', write: 'Écrire', translate: 'Traduire', pricing: 'Tarifs', help: 'Aide', faq: 'FAQ', legal: 'Légal', terms: 'Conditions', privacy: 'Confidentialité', contact: 'Contact' },
        common: { loading: 'Chargement...', save: 'Enregistrer', cancel: 'Annuler', delete: 'Supprimer', edit: 'Modifier', submit: 'Soumettre', search: 'Rechercher', filter: 'Filtrer', all: 'Tout', none: 'Aucun', yes: 'Oui', no: 'Non', back: 'Retour', next: 'Suivant', previous: 'Précédent', free: 'Gratuit' }
    },
    de: {
        nav: { home: 'Startseite', browse: 'Durchsuchen', genres: 'Genres', revenue: 'Umsatz', upload: 'Hochladen', dashboard: 'Dashboard', register: 'Registrieren', login: 'Anmelden', logout: 'Abmelden', getStarted: 'Loslegen', author: 'Autor', translator: 'Übersetzer', editor: 'Redakteur', notifications: 'Benachrichtigungen', settings: 'Einstellungen', support: 'Support' },
        home: { hero: { title: 'Entdecke Geschichten', subtitle: '9 Sprachen', startReading: 'Lesen', startWriting: 'Schreiben', availableIn: '9 Sprachen' }, featured: { title: 'Ausgewählt', viewAll: 'Alle' }, howItWorks: { title: 'Wie es funktioniert', step1: { title: 'Schreiben', desc: 'Geschichte' }, step2: { title: 'KI', desc: 'Übersetzung' }, step3: { title: 'Verdienen', desc: '60%' } }, stats: { languages: 'Sprachen', works: 'Werke', authors: 'Autoren', readers: 'Leser' }, forCreators: { title: 'Kreative', desc: 'Beitreten', feature1: 'Gratis KI', feature2: '60%', feature3: 'Global', feature4: 'Rechte', button: 'Erstellen' }, revenue: { title: 'Verteilung', platform: 'Plattform' }, cta: { title: 'Bereit?', subtitle: 'Beitreten', createAccount: 'Konto', browseWorks: 'Durchsuchen' } },
        login: { welcomeBack: 'Willkommen', subtitle: 'Anmelden', email: 'Email', emailPlaceholder: 'Email', password: 'Passwort', passwordPlaceholder: 'Passwort', rememberMe: 'Erinnern', forgotPassword: 'Vergessen?', signIn: 'Anmelden', orContinueWith: 'oder', noAccount: 'Kein Konto?', signUpFree: 'Registrieren' },
        register: { title: 'Konto Erstellen', subtitle: 'Beitreten', roles: { reader: 'Leser', readerDesc: 'Entdecken', author: 'Autor', authorDesc: 'Schreiben', translator: 'Übersetzer', translatorDesc: 'Übersetzen' }, firstName: 'Vorname', firstNamePlaceholder: 'Vorname', lastName: 'Nachname', lastNamePlaceholder: 'Nachname', createPassword: 'Passwort', preferredLanguage: 'Sprache', agreeToTerms: 'Ich stimme zu', and: 'und', createAccount: 'Erstellen', orSignUpWith: 'oder', haveAccount: 'Bereits registriert?' },
        dashboard: { title: 'Dashboard', welcome: 'Willkommen', overview: 'Übersicht', myWorks: 'Werke', earnings: 'Einnahmen', analytics: 'Analysen', recentActivity: 'Aktivität', quickActions: 'Aktionen', uploadNew: 'Hochladen', viewAll: 'Alle', totalRevenue: 'Einnahmen', thisMonth: 'Dieser Monat', totalViews: 'Aufrufe', totalWorks: 'Werke', followers: 'Follower' },
        browse: { title: 'Durchsuchen', subtitle: 'Entdecken', category: 'Kategorie', allCategories: 'Alle', language: 'Sprache', allLanguages: 'Alle', sortBy: 'Sortieren', mostPopular: 'Beliebt', newest: 'Neu', highestRated: 'Bewertet', priceLowHigh: 'Preis', applyFilters: 'Anwenden' },
        notifications: { title: 'Benachrichtigungen', subtitle: 'Anzeigen', settings: 'Einstellungen', all: 'Alle', unread: 'Ungelesen', today: 'Heute', thisWeek: 'Woche', allTypes: 'Alle', unreadOnly: 'Ungelesene', markAllRead: 'Markieren', clearRead: 'Löschen', clearAll: 'Alle' },
        analytics: { title: 'Analysen', subtitle: 'Leistung', overview: 'Übersicht', views: 'Aufrufe', revenue: 'Einnahmen', followers: 'Follower', thisMonth: 'Dieser Monat', lastMonth: 'Letzter', growth: 'Wachstum', topWorks: 'Top', byViews: 'Aufrufe', byRevenue: 'Einnahmen' },
        upload: { title: 'Hochladen', subtitle: 'Teilen', dragDrop: 'Ziehen', or: 'oder', browseFiles: 'Durchsuchen', supportedFormats: 'Formate', workTitle: 'Titel', description: 'Beschreibung', category: 'Kategorie', language: 'Sprache', pricing: 'Preis', publishNow: 'Veröffentlichen', saveDraft: 'Entwurf' },
        checkout: { title: 'Kasse', orderSummary: 'Zusammenfassung', subtotal: 'Zwischensumme', tax: 'Steuer', total: 'Gesamt', paymentMethod: 'Methode', creditCard: 'Karte', paypal: 'PayPal', completeOrder: 'Abschließen', securePayment: 'Sicher' },
        payment: { successTitle: 'Zahlung Erfolgreich', cancelTitle: 'Zahlung Abgebrochen', success: 'Zahlung Erfolgreich!', cancelled: 'Zahlung Abgebrochen', thankYou: 'Vielen Dank für Ihren Kauf. Ihr Inhalt ist verfügbar.', noCharge: 'Ihre Zahlung wurde nicht abgeschlossen. Keine Gebühren.', orderDetails: 'Bestelldetails', orderId: 'Bestell-ID:', item: 'Artikel:', amountPaid: 'Betrag:', date: 'Datum:', supportingCreators: 'Kreative Unterstützen:', revenueInfo: 'Ihr Kauf unterstützt den Autor (40%), Übersetzer (20%) und Redakteur (10%).', startReading: 'Lesen Beginnen', backToHome: 'Zurück zur Startseite', receiptSent: 'Eine Quittung wurde an Ihre E-Mail gesendet', possibleReasons: 'Dies könnte passiert sein weil:', reason1: 'Sie auf die Zurück-Taste geklickt haben', reason2: 'Die Zahlungssitzung abgelaufen ist', reason3: 'Es ein Problem mit Ihrer Zahlungsmethode gab', needHelp: 'Brauchen Sie Hilfe?', contactSupport: 'Kontaktieren Sie unser Support-Team', tryAgain: 'Erneut Versuchen', secureInfo: 'Ihre Zahlungsinformationen sind immer sicher' },
        translation: { pageTitle: 'Übersetzungsstatus', title: 'Übersetzungsstatus', backToDashboard: 'Zurück zum Dashboard', original: 'Original', totalTranslations: 'Übersetzungen', completed: 'Fertig', inProgress: 'In Bearbeitung', overallProgress: 'Gesamtfortschritt', targetLanguage: 'Zielsprache', progress: 'Fortschritt', statusCompleted: 'Fertig', translating: 'Übersetze...', processing: 'Verarbeite', queued: 'In Warteschlange', waiting: 'Wartet', view: 'Ansehen', aiTranslation: 'KI-Übersetzung', completed2HoursAgo: 'Vor 2h fertig', estRemaining: 'Ca. 3 Min übrig', scheduledSoon: 'Bald', reviewed: 'Geprüft', professionalReview: 'Profi-Review', options: 'Übersetzungsoptionen', addLanguages: 'Sprachen hinzufügen', requestReview: 'Review anfordern' },
        footer: { tagline: 'Mehrsprachige Plattform', explore: 'Entdecken', authors: 'Autoren', creators: 'Kreative', write: 'Schreiben', translate: 'Übersetzen', pricing: 'Preise', help: 'Hilfe', faq: 'FAQ', legal: 'Rechtliches', terms: 'Bedingungen', privacy: 'Datenschutz', contact: 'Kontakt' },
        common: { loading: 'Laden...', save: 'Speichern', cancel: 'Abbrechen', delete: 'Löschen', edit: 'Bearbeiten', submit: 'Absenden', search: 'Suchen', filter: 'Filtern', all: 'Alle', none: 'Keine', yes: 'Ja', no: 'Nein', back: 'Zurück', next: 'Weiter', previous: 'Zurück', free: 'Kostenlos' }
    },
    ko: {
        nav: { home: '홈', browse: '둘러보기', genres: '장르', revenue: '수익', upload: '업로드', dashboard: '대시보드', register: '등록', login: '로그인', logout: '로그아웃', getStarted: '시작', author: '저자', translator: '번역가', editor: '편집자', notifications: '알림', settings: '설정', support: '지원' },
        home: { hero: { title: '이야기 발견', subtitle: '9개 언어', startReading: '읽기', startWriting: '쓰기', availableIn: '9개 언어' }, featured: { title: '추천', viewAll: '모두' }, howItWorks: { title: '사용법', step1: { title: '작성', desc: '이야기' }, step2: { title: 'AI', desc: '번역' }, step3: { title: '수익', desc: '60%' } }, stats: { languages: '언어', works: '작품', authors: '저자', readers: '독자' }, forCreators: { title: '창작자', desc: '참여', feature1: '무료 AI', feature2: '60%', feature3: '글로벌', feature4: '권리', button: '창작' }, revenue: { title: '분배', platform: '플랫폼' }, cta: { title: '준비?', subtitle: '참여', createAccount: '계정', browseWorks: '둘러보기' } },
        login: { welcomeBack: '환영', subtitle: '로그인', email: '이메일', emailPlaceholder: '이메일', password: '비밀번호', passwordPlaceholder: '비밀번호', rememberMe: '기억', forgotPassword: '잊음?', signIn: '로그인', orContinueWith: '또는', noAccount: '계정 없음?', signUpFree: '가입' },
        register: { title: '계정 만들기', subtitle: '참여', roles: { reader: '독자', readerDesc: '발견', author: '저자', authorDesc: '작성', translator: '번역가', translatorDesc: '번역' }, firstName: '이름', firstNamePlaceholder: '이름', lastName: '성', lastNamePlaceholder: '성', createPassword: '비밀번호', preferredLanguage: '언어', agreeToTerms: '동의', and: '및', createAccount: '만들기', orSignUpWith: '또는', haveAccount: '계정 있음?' },
        dashboard: { title: '대시보드', welcome: '환영', overview: '개요', myWorks: '작품', earnings: '수익', analytics: '분석', recentActivity: '활동', quickActions: '작업', uploadNew: '업로드', viewAll: '모두', totalRevenue: '수익', thisMonth: '이번 달', totalViews: '조회수', totalWorks: '작품', followers: '팔로워' },
        browse: { title: '둘러보기', subtitle: '발견', category: '카테고리', allCategories: '모두', language: '언어', allLanguages: '모두', sortBy: '정렬', mostPopular: '인기', newest: '최신', highestRated: '평점', priceLowHigh: '가격', applyFilters: '적용' },
        notifications: { title: '알림', subtitle: '보기', settings: '설정', all: '전체', unread: '읽지 않음', today: '오늘', thisWeek: '이번 주', allTypes: '모든', unreadOnly: '읽지 않음', markAllRead: '읽음', clearRead: '삭제', clearAll: '모두' },
        analytics: { title: '분석', subtitle: '성과', overview: '개요', views: '조회수', revenue: '수익', followers: '팔로워', thisMonth: '이번 달', lastMonth: '지난 달', growth: '성장', topWorks: '인기', byViews: '조회수', byRevenue: '수익' },
        upload: { title: '업로드', subtitle: '공유', dragDrop: '드래그', or: '또는', browseFiles: '찾기', supportedFormats: '형식', workTitle: '제목', description: '설명', category: '카테고리', language: '언어', pricing: '가격', publishNow: '발행', saveDraft: '저장' },
        checkout: { title: '결제', orderSummary: '요약', subtotal: '소계', tax: '세금', total: '합계', paymentMethod: '방법', creditCard: '카드', paypal: 'PayPal', completeOrder: '완료', securePayment: '안전' },
        payment: { successTitle: '결제 성공', cancelTitle: '결제 취소', success: '결제 성공!', cancelled: '결제 취소됨', thankYou: '구매해 주셔서 감사합니다. 콘텐츠를 이용하실 수 있습니다.', noCharge: '결제가 완료되지 않았습니다. 청구되지 않았습니다.', orderDetails: '주문 상세', orderId: '주문 ID:', item: '상품:', amountPaid: '결제 금액:', date: '날짜:', supportingCreators: '창작자 지원:', revenueInfo: '구매는 저자(40%), 번역가(20%), 편집자(10%)를 직접 지원합니다.', startReading: '읽기 시작', backToHome: '홈으로 돌아가기', receiptSent: '영수증이 이메일로 발송되었습니다', possibleReasons: '다음과 같은 이유일 수 있습니다:', reason1: '뒤로 버튼을 클릭하거나 결제 창을 닫았습니다', reason2: '결제 세션이 만료되었습니다', reason3: '결제 방법에 문제가 있었습니다', needHelp: '도움이 필요하신가요?', contactSupport: '지원팀에 문의하세요', tryAgain: '다시 시도', secureInfo: '결제 정보는 항상 안전합니다' },
        translation: { pageTitle: '번역 상태', title: '번역 상태', backToDashboard: '대시보드로 돌아가기', original: '원본', totalTranslations: '총 번역', completed: '완료', inProgress: '진행 중', overallProgress: '전체 진행률', targetLanguage: '대상 언어', progress: '진행률', statusCompleted: '완료', translating: '번역 중...', processing: '처리 중', queued: '대기 중', waiting: '대기 중', view: '보기', aiTranslation: 'AI 번역', completed2HoursAgo: '2시간 전 완료', estRemaining: '약 3분 남음', scheduledSoon: '곧 시작', reviewed: '검토됨', professionalReview: '전문 검토', options: '번역 옵션', addLanguages: '언어 추가', requestReview: '전문 검토 요청' },
        footer: { tagline: '다국어 플랫폼', explore: '탐색', authors: '저자', creators: '창작자', write: '쓰기', translate: '번역', pricing: '가격', help: '도움말', faq: 'FAQ', legal: '법적', terms: '약관', privacy: '개인정보', contact: '연락처' },
        common: { loading: '로딩...', save: '저장', cancel: '취소', delete: '삭제', edit: '편집', submit: '제출', search: '검색', filter: '필터', all: '전체', none: '없음', yes: '예', no: '아니오', back: '뒤로', next: '다음', previous: '이전', free: '무료' }
    },
    ar: {
        nav: { home: 'الرئيسية', browse: 'تصفح', genres: 'الأنواع', revenue: 'الإيرادات', upload: 'رفع', dashboard: 'لوحة', register: 'تسجيل', login: 'دخول', logout: 'خروج', getStarted: 'ابدأ', author: 'مؤلف', translator: 'مترجم', editor: 'محرر', notifications: 'إشعارات', settings: 'إعدادات', support: 'دعم' },
        home: { hero: { title: 'اكتشف قصص', subtitle: '9 لغات', startReading: 'اقرأ', startWriting: 'اكتب', availableIn: '9 لغات' }, featured: { title: 'مميز', viewAll: 'الكل' }, howItWorks: { title: 'كيف', step1: { title: 'اكتب', desc: 'قصة' }, step2: { title: 'AI', desc: 'ترجمة' }, step3: { title: 'اكسب', desc: '60%' } }, stats: { languages: 'لغات', works: 'أعمال', authors: 'مؤلفون', readers: 'قراء' }, forCreators: { title: 'مبدعين', desc: 'انضم', feature1: 'AI مجاني', feature2: '60%', feature3: 'عالمي', feature4: 'حقوق', button: 'إبدأ' }, revenue: { title: 'توزيع', platform: 'منصة' }, cta: { title: 'مستعد?', subtitle: 'انضم', createAccount: 'حساب', browseWorks: 'تصفح' } },
        login: { welcomeBack: 'مرحباً', subtitle: 'دخول', email: 'بريد', emailPlaceholder: 'بريد', password: 'كلمة مرور', passwordPlaceholder: 'كلمة مرور', rememberMe: 'تذكر', forgotPassword: 'نسيت?', signIn: 'دخول', orContinueWith: 'أو', noAccount: 'لا حساب?', signUpFree: 'سجل' },
        register: { title: 'إنشاء حساب', subtitle: 'انضم', roles: { reader: 'قارئ', readerDesc: 'اكتشف', author: 'مؤلف', authorDesc: 'اكتب', translator: 'مترجم', translatorDesc: 'ترجم' }, firstName: 'الاسم', firstNamePlaceholder: 'الاسم', lastName: 'اللقب', lastNamePlaceholder: 'اللقب', createPassword: 'كلمة مرور', preferredLanguage: 'لغة', agreeToTerms: 'أوافق', and: 'و', createAccount: 'إنشاء', orSignUpWith: 'أو', haveAccount: 'لديك حساب?' },
        dashboard: { title: 'لوحة', welcome: 'مرحباً', overview: 'نظرة', myWorks: 'أعمال', earnings: 'أرباح', analytics: 'تحليلات', recentActivity: 'نشاط', quickActions: 'إجراءات', uploadNew: 'رفع', viewAll: 'الكل', totalRevenue: 'إيرادات', thisMonth: 'الشهر', totalViews: 'مشاهدات', totalWorks: 'أعمال', followers: 'متابعون' },
        browse: { title: 'تصفح', subtitle: 'اكتشف', category: 'فئة', allCategories: 'الكل', language: 'لغة', allLanguages: 'الكل', sortBy: 'ترتيب', mostPopular: 'شائع', newest: 'جديد', highestRated: 'تقييم', priceLowHigh: 'سعر', applyFilters: 'تطبيق' },
        notifications: { title: 'إشعارات', subtitle: 'عرض', settings: 'إعدادات', all: 'الكل', unread: 'غير مقروء', today: 'اليوم', thisWeek: 'الأسبوع', allTypes: 'الكل', unreadOnly: 'غير مقروء', markAllRead: 'قراءة', clearRead: 'مسح', clearAll: 'الكل' },
        analytics: { title: 'تحليلات', subtitle: 'أداء', overview: 'نظرة', views: 'مشاهدات', revenue: 'إيرادات', followers: 'متابعون', thisMonth: 'الشهر', lastMonth: 'الماضي', growth: 'نمو', topWorks: 'أفضل', byViews: 'مشاهدات', byRevenue: 'إيرادات' },
        upload: { title: 'رفع', subtitle: 'شارك', dragDrop: 'اسحب', or: 'أو', browseFiles: 'تصفح', supportedFormats: 'صيغ', workTitle: 'عنوان', description: 'وصف', category: 'فئة', language: 'لغة', pricing: 'سعر', publishNow: 'نشر', saveDraft: 'حفظ' },
        checkout: { title: 'دفع', orderSummary: 'ملخص', subtotal: 'فرعي', tax: 'ضريبة', total: 'مجموع', paymentMethod: 'طريقة', creditCard: 'بطاقة', paypal: 'PayPal', completeOrder: 'إتمام', securePayment: 'آمن' },
        payment: { successTitle: 'نجح الدفع', cancelTitle: 'تم إلغاء الدفع', success: 'نجح الدفع!', cancelled: 'تم إلغاء الدفع', thankYou: 'شكراً لشرائك. المحتوى متاح الآن.', noCharge: 'لم يتم الدفع. لم يتم خصم أي مبلغ.', orderDetails: 'تفاصيل الطلب', orderId: 'رقم الطلب:', item: 'المنتج:', amountPaid: 'المبلغ المدفوع:', date: 'التاريخ:', supportingCreators: 'دعم المبدعين:', revenueInfo: 'شراؤك يدعم المؤلف (40%) والمترجم (20%) والمحرر (10%).', startReading: 'ابدأ القراءة', backToHome: 'العودة للرئيسية', receiptSent: 'تم إرسال إيصال إلى بريدك', possibleReasons: 'قد يكون هذا بسبب:', reason1: 'نقرت على زر الرجوع أو أغلقت نافذة الدفع', reason2: 'انتهت صلاحية جلسة الدفع', reason3: 'كان هناك مشكلة في طريقة الدفع', needHelp: 'تحتاج مساعدة?', contactSupport: 'تواصل مع فريق الدعم', tryAgain: 'حاول مرة أخرى', secureInfo: 'معلومات الدفع آمنة دائماً' },
        translation: { pageTitle: 'حالة الترجمة', title: 'حالة الترجمة', backToDashboard: 'العودة للوحة', original: 'الأصل', totalTranslations: 'الترجمات', completed: 'مكتملة', inProgress: 'جارية', overallProgress: 'التقدم الكلي', targetLanguage: 'اللغة الهدف', progress: 'التقدم', statusCompleted: 'مكتمل', translating: 'جاري الترجمة...', processing: 'معالجة', queued: 'في الانتظار', waiting: 'انتظار', view: 'عرض', aiTranslation: 'ترجمة AI', completed2HoursAgo: 'اكتمل قبل ساعتين', estRemaining: 'تقريباً 3 دقائق', scheduledSoon: 'قريباً', reviewed: 'تمت المراجعة', professionalReview: 'مراجعة احترافية', options: 'خيارات الترجمة', addLanguages: 'إضافة لغات', requestReview: 'طلب مراجعة' },
        footer: { tagline: 'منصة متعددة', explore: 'استكشف', authors: 'مؤلفون', creators: 'مبدعون', write: 'اكتب', translate: 'ترجم', pricing: 'أسعار', help: 'مساعدة', faq: 'أسئلة', legal: 'قانوني', terms: 'شروط', privacy: 'خصوصية', contact: 'اتصل' },
        common: { loading: 'تحميل...', save: 'حفظ', cancel: 'إلغاء', delete: 'حذف', edit: 'تعديل', submit: 'إرسال', search: 'بحث', filter: 'تصفية', all: 'الكل', none: 'لا شيء', yes: 'نعم', no: 'لا', back: 'رجوع', next: 'التالي', previous: 'السابق', free: 'مجاني' }
    },
    pt: {
        nav: { home: 'Início', browse: 'Explorar', genres: 'Gêneros', revenue: 'Receita', upload: 'Enviar', dashboard: 'Painel', register: 'Registrar', login: 'Entrar', logout: 'Sair', getStarted: 'Começar', author: 'Autor', translator: 'Tradutor', editor: 'Editor', notifications: 'Notificações', settings: 'Configurações', support: 'Suporte' },
        home: { hero: { title: 'Descubra Histórias', subtitle: '9 idiomas', startReading: 'Ler', startWriting: 'Escrever', availableIn: '9 idiomas' }, featured: { title: 'Destaque', viewAll: 'Tudo' }, howItWorks: { title: 'Como Funciona', step1: { title: 'Escreva', desc: 'História' }, step2: { title: 'IA', desc: 'Tradução' }, step3: { title: 'Ganhe', desc: '60%' } }, stats: { languages: 'Idiomas', works: 'Obras', authors: 'Autores', readers: 'Leitores' }, forCreators: { title: 'Criadores', desc: 'Junte-se', feature1: 'IA grátis', feature2: '60%', feature3: 'Global', feature4: 'Direitos', button: 'Criar' }, revenue: { title: 'Distribuição', platform: 'Plataforma' }, cta: { title: 'Pronto?', subtitle: 'Junte-se', createAccount: 'Conta', browseWorks: 'Explorar' } },
        login: { welcomeBack: 'Bem-vindo', subtitle: 'Entrar', email: 'Email', emailPlaceholder: 'Email', password: 'Senha', passwordPlaceholder: 'Senha', rememberMe: 'Lembrar', forgotPassword: 'Esqueceu?', signIn: 'Entrar', orContinueWith: 'ou', noAccount: 'Sem conta?', signUpFree: 'Cadastre-se' },
        register: { title: 'Criar Conta', subtitle: 'Junte-se', roles: { reader: 'Leitor', readerDesc: 'Descubra', author: 'Autor', authorDesc: 'Escreva', translator: 'Tradutor', translatorDesc: 'Traduza' }, firstName: 'Nome', firstNamePlaceholder: 'Nome', lastName: 'Sobrenome', lastNamePlaceholder: 'Sobrenome', createPassword: 'Senha', preferredLanguage: 'Idioma', agreeToTerms: 'Concordo', and: 'e', createAccount: 'Criar', orSignUpWith: 'ou', haveAccount: 'Já tem conta?' },
        dashboard: { title: 'Painel', welcome: 'Bem-vindo', overview: 'Visão', myWorks: 'Obras', earnings: 'Ganhos', analytics: 'Análises', recentActivity: 'Atividade', quickActions: 'Ações', uploadNew: 'Enviar', viewAll: 'Tudo', totalRevenue: 'Receita', thisMonth: 'Este Mês', totalViews: 'Visualizações', totalWorks: 'Obras', followers: 'Seguidores' },
        browse: { title: 'Explorar', subtitle: 'Descubra', category: 'Categoria', allCategories: 'Todas', language: 'Idioma', allLanguages: 'Todos', sortBy: 'Ordenar', mostPopular: 'Popular', newest: 'Recente', highestRated: 'Avaliado', priceLowHigh: 'Preço', applyFilters: 'Aplicar' },
        notifications: { title: 'Notificações', subtitle: 'Ver', settings: 'Configurações', all: 'Todas', unread: 'Não Lidas', today: 'Hoje', thisWeek: 'Semana', allTypes: 'Todos', unreadOnly: 'Não Lidas', markAllRead: 'Marcar', clearRead: 'Limpar', clearAll: 'Todas' },
        analytics: { title: 'Análises', subtitle: 'Desempenho', overview: 'Visão', views: 'Visualizações', revenue: 'Receita', followers: 'Seguidores', thisMonth: 'Este Mês', lastMonth: 'Passado', growth: 'Crescimento', topWorks: 'Melhores', byViews: 'Visualizações', byRevenue: 'Receita' },
        upload: { title: 'Enviar', subtitle: 'Compartilhe', dragDrop: 'Arraste', or: 'ou', browseFiles: 'Procurar', supportedFormats: 'Formatos', workTitle: 'Título', description: 'Descrição', category: 'Categoria', language: 'Idioma', pricing: 'Preço', publishNow: 'Publicar', saveDraft: 'Rascunho' },
        checkout: { title: 'Pagamento', orderSummary: 'Resumo', subtotal: 'Subtotal', tax: 'Imposto', total: 'Total', paymentMethod: 'Método', creditCard: 'Cartão', paypal: 'PayPal', completeOrder: 'Finalizar', securePayment: 'Seguro' },
        payment: { successTitle: 'Pagamento Bem-sucedido', cancelTitle: 'Pagamento Cancelado', success: 'Pagamento Bem-sucedido!', cancelled: 'Pagamento Cancelado', thankYou: 'Obrigado pela sua compra. Seu conteúdo está disponível.', noCharge: 'Seu pagamento não foi concluído. Nenhuma cobrança foi feita.', orderDetails: 'Detalhes do Pedido', orderId: 'ID do Pedido:', item: 'Item:', amountPaid: 'Valor Pago:', date: 'Data:', supportingCreators: 'Apoiando Criadores:', revenueInfo: 'Sua compra apoia o autor (40%), tradutor (20%) e editor (10%).', startReading: 'Começar a Ler', backToHome: 'Voltar ao Início', receiptSent: 'Um recibo foi enviado para seu email', possibleReasons: 'Isso pode ter acontecido porque:', reason1: 'Você clicou no botão voltar ou fechou a janela de pagamento', reason2: 'A sessão de pagamento expirou', reason3: 'Houve um problema com seu método de pagamento', needHelp: 'Precisa de Ajuda?', contactSupport: 'Entre em contato com nossa equipe de suporte', tryAgain: 'Tentar Novamente', secureInfo: 'Suas informações de pagamento estão sempre seguras' },
        translation: { pageTitle: 'Status de Tradução', title: 'Status de Tradução', backToDashboard: 'Voltar ao Painel', original: 'Original', totalTranslations: 'Traduções', completed: 'Concluídas', inProgress: 'Em Progresso', overallProgress: 'Progresso Geral', targetLanguage: 'Idioma Alvo', progress: 'Progresso', statusCompleted: 'Concluído', translating: 'Traduzindo...', processing: 'Processando', queued: 'Na Fila', waiting: 'Aguardando', view: 'Ver', aiTranslation: 'Tradução IA', completed2HoursAgo: 'Concluído há 2h', estRemaining: 'Est. 3 min restantes', scheduledSoon: 'Em breve', reviewed: 'Revisado', professionalReview: 'Revisão Profissional', options: 'Opções de Tradução', addLanguages: 'Adicionar Idiomas', requestReview: 'Solicitar Revisão' },
        footer: { tagline: 'Plataforma multilíngue', explore: 'Explorar', authors: 'Autores', creators: 'Criadores', write: 'Escrever', translate: 'Traduzir', pricing: 'Preços', help: 'Ajuda', faq: 'FAQ', legal: 'Legal', terms: 'Termos', privacy: 'Privacidade', contact: 'Contato' },
        common: { loading: 'Carregando...', save: 'Salvar', cancel: 'Cancelar', delete: 'Excluir', edit: 'Editar', submit: 'Enviar', search: 'Buscar', filter: 'Filtrar', all: 'Todos', none: 'Nenhum', yes: 'Sim', no: 'Não', back: 'Voltar', next: 'Próximo', previous: 'Anterior', free: 'Grátis' }
    }
};

const availableLanguages = {
    en: { name: 'English', nativeName: 'English', flag: '🇬🇧', rtl: false },
    ja: { name: 'Japanese', nativeName: '日本語', flag: '🇯🇵', rtl: false },
    zh: { name: 'Chinese', nativeName: '中文', flag: '🇨🇳', rtl: false },
    es: { name: 'Spanish', nativeName: 'Español', flag: '🇪🇸', rtl: false },
    fr: { name: 'French', nativeName: 'Français', flag: '🇫🇷', rtl: false },
    de: { name: 'German', nativeName: 'Deutsch', flag: '🇩🇪', rtl: false },
    ko: { name: 'Korean', nativeName: '한국어', flag: '🇰🇷', rtl: false },
    ar: { name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦', rtl: true },
    pt: { name: 'Portuguese', nativeName: 'Português', flag: '🇧🇷', rtl: false }
};

function t(key, lang = null) {
    const currentLang = lang || getCurrentLanguage();
    const keys = key.split('.');
    let result = translations[currentLang];
    for (const k of keys) {
        if (result && result[k]) { result = result[k]; }
        else {
            result = translations.en;
            for (const fallbackKey of keys) {
                if (result && result[fallbackKey]) { result = result[fallbackKey]; }
                else { return key; }
            }
            break;
        }
    }
    return typeof result === 'string' ? result : key;
}

function getCurrentLanguage() {
    return localStorage.getItem('preferredLanguage') || navigator.language.split('-')[0] || 'en';
}

function setLanguage(lang) {
    if (availableLanguages[lang]) {
        localStorage.setItem('preferredLanguage', lang);
        document.documentElement.dir = availableLanguages[lang].rtl ? 'rtl' : 'ltr';
        document.documentElement.lang = lang;
        document.dispatchEvent(new CustomEvent('languageChanged', { detail: { lang } }));
    }
}

function isLanguageAvailable(lang) { return !!availableLanguages[lang]; }

window.translations = translations;
window.availableLanguages = availableLanguages;
window.t = t;
window.getCurrentLanguage = getCurrentLanguage;
window.setLanguage = setLanguage;
window.isLanguageAvailable = isLanguageAvailable;
