/**
 * Publisher Platform - Japanese Translations (日本語)
 * Split from translations.js for better maintainability
 */

// Initialize translations object if not exists
if (typeof window.translations === 'undefined') {
    window.translations = {};
}

window.translations.ja = {
        nav: { home: 'ホーム', browse: '作品を探す', genres: 'ジャンル', revenue: '収益配分', upload: '作品アップロード', dashboard: 'ダッシュボード', register: '登録', login: 'ログイン', logout: 'ログアウト', getStarted: '今すぐ始める', author: '著者', translator: '翻訳者', editor: '編集者', notifications: '通知', settings: '設定', support: 'サポート', accountSettings: 'アカウント設定', creatorDashboard: 'クリエイターダッシュボード', library: 'ライブラリ', translationTools: '翻訳ツール', mangaTranslator: 'マンガ翻訳', translationStatus: '翻訳状況', findTranslators: '翻訳者を探す', contact: 'お問い合わせ' },
        home: { hero: { title: '世界中の物語を発見しよう', subtitle: '9言語で物語を読んで出版', startReading: '読み始める', startWriting: '書き始める', availableIn: '9言語に対応' }, featured: { title: '注目の作品', viewAll: 'すべての作品を見る' }, howItWorks: { title: '使い方', step1: { title: '書いてアップロード', desc: 'あなたの物語を作成' }, step2: { title: 'AI翻訳', desc: '9言語に即座翻訳' }, step3: { title: '収益を得る', desc: '最大60%獲得' } }, stats: { languages: '言語', works: '作品', authors: '著者', readers: '読者' }, forCreators: { title: 'クリエイターのために', desc: 'コミュニティに参加', feature1: '無料AI翻訳', feature2: '最大60%収益', feature3: 'グローバルリーチ', feature4: '権利を保持', button: '創作を始める' }, revenue: { title: '収益配分', platform: 'プラットフォーム' }, cta: { title: '始める準備はできましたか？', subtitle: 'クリエイターに参加', createAccount: '無料アカウント作成', browseWorks: '作品を探す' } },
        login: { welcomeBack: 'おかえりなさい', subtitle: 'ログインして続ける', email: 'メールアドレス', emailPlaceholder: 'メールを入力', password: 'パスワード', passwordPlaceholder: 'パスワードを入力', rememberMe: 'ログイン状態を保持', forgotPassword: 'パスワードを忘れた？', signIn: 'ログイン', orContinueWith: 'または', noAccount: 'アカウントをお持ちでない？', signUpFree: '無料で登録' },
        register: { title: 'アカウント作成', subtitle: '世界中の読者と参加', roles: { reader: '読者', readerDesc: '物語を発見', author: '著者', authorDesc: '執筆・出版', translator: '翻訳者', translatorDesc: '作品を翻訳' }, firstName: '名', firstNamePlaceholder: '名', lastName: '姓', lastNamePlaceholder: '姓', createPassword: 'パスワード作成', preferredLanguage: '優先言語', agreeToTerms: '同意します', and: 'および', createAccount: 'アカウント作成', orSignUpWith: 'または登録', haveAccount: 'アカウントをお持ち？' },
        dashboard: { title: 'ダッシュボード', welcome: 'おかえりなさい', overview: '概要', myWorks: '自分の作品', earnings: '収益', analytics: '分析', recentActivity: '最近のアクティビティ', quickActions: 'クイックアクション', uploadNew: '新しい作品をアップロード', viewAll: 'すべて見る', totalRevenue: '総収益', thisMonth: '今月', totalViews: '総閲覧数', totalWorks: '総作品数', followers: 'フォロワー', translations: '翻訳数', recentTranslations: '最近の翻訳', subtitle: '今日のあなたの作品の状況です。', aiTranslation: { title: 'AI翻訳', freeTier: '無料プラン', worksTranslated: '今月翻訳した作品数', freeRemaining: '無料翻訳残り2回' }, actions: { create: '作成', newWork: '新規作品', upload: 'アップロード', fileUpload: 'ファイルアップロード', manga: 'マンガ', translator: '翻訳', reader: 'リーダー', preview: 'プレビュー' } },
        browse: { title: '作品を探す', subtitle: '素晴らしい物語を発見', category: 'カテゴリ', allCategories: 'すべてのカテゴリ', language: '言語', allLanguages: 'すべての言語', sortBy: '並び替え', mostPopular: '人気順', newest: '新着順', highestRated: '評価順', priceLowHigh: '価格: 低い順', applyFilters: 'フィルターを適用' },
        notifications: { title: '通知センター', subtitle: '通知を確認', settings: '通知設定', all: '全通知', unread: '未読', today: '今日', thisWeek: '今週', allTypes: 'すべてのタイプ', unreadOnly: '未読のみ', markAllRead: 'すべて既読', clearRead: '既読を削除', clearAll: 'すべて削除' },
        analytics: { title: 'アナリティクス', subtitle: 'パフォーマンスを追跡', overview: '概要', views: '閲覧数', revenue: '収益', followers: 'フォロワー', thisMonth: '今月', lastMonth: '先月', growth: '成長率', topWorks: '人気作品', byViews: '閲覧数順', byRevenue: '収益順', period: '期間', days7: '7日間', days30: '30日間', days90: '90日間', lastUpdate: '最終更新', readingTime: '読書時間', engagement: 'エンゲージメント', likes: 'いいね', comments: 'コメント', bookmarks: 'ブックマーク', downloads: 'ダウンロード', workTitle: 'タイトル', readers: '読者数', noData: 'データがありません', loadFailed: 'データの読み込みに失敗', trend: 'トレンド' },
        upload: { title: '作品アップロード', subtitle: '作品を世界に共有', dragDrop: 'ファイルをドラッグ＆ドロップ', or: 'または', browseFiles: 'ファイルを選択', supportedFormats: '対応フォーマット', workTitle: '作品タイトル', description: '説明', category: 'カテゴリ', language: '言語', pricing: '価格設定', publishNow: '今すぐ公開', saveDraft: '下書き保存' },
        checkout: { title: 'お支払い', orderSummary: '注文内容', subtotal: '小計', tax: '税金', total: '合計', paymentMethod: '支払い方法', creditCard: 'クレジットカード', paypal: 'PayPal', completeOrder: '注文を確定', securePayment: '安全な決済' },
        payment: { successTitle: '支払い完了', cancelTitle: '支払いキャンセル', success: '支払いが完了しました！', cancelled: '支払いがキャンセルされました', thankYou: 'ご購入ありがとうございます。', noCharge: '請求はされていません。', orderDetails: '注文詳細', orderId: '注文ID:', item: '商品:', amountPaid: '支払い金額:', date: '日付:', supportingCreators: 'クリエイターをサポート:', revenueInfo: 'ご購入は著者(40%)、翻訳者(20%)、編集者(10%)を直接支援します。', startReading: '読み始める', backToHome: 'ホームに戻る', receiptSent: '領収書をメールで送信しました', possibleReasons: '以下の理由が考えられます：', reason1: '戻るボタンを押した', reason2: 'セッションがタイムアウト', reason3: '支払い方法に問題', needHelp: 'お困りですか？', contactSupport: 'サポートに連絡', tryAgain: 'もう一度試す', secureInfo: '安全な決済' },
        translation: { pageTitle: '翻訳ステータス', title: '翻訳ステータス', backToDashboard: 'ダッシュボードに戻る', original: '原文', totalTranslations: '翻訳総数', completed: '完了', inProgress: '進行中', overallProgress: '全体進捗', targetLanguage: '翻訳先言語', progress: '進捗', statusCompleted: '完了', translating: '翻訳中...', processing: '処理中', queued: '待機中', waiting: '待機中', view: '表示', aiTranslation: 'AI翻訳', completed2HoursAgo: '2時間前に完了', estRemaining: '残り約3分', scheduledSoon: 'まもなく開始', reviewed: 'レビュー済', professionalReview: 'プロレビュー', options: '翻訳オプション', addLanguages: '言語を追加', requestReview: 'プロレビューを依頼' },
        accountSettings: { title: 'アカウント設定', subtitle: 'プロフィール、セキュリティ、通知などの設定を管理', tabs: { profile: 'プロフィール', security: 'セキュリティ', notifications: '通知', purchases: '購入履歴', danger: 'アカウント削除' }, profile: { image: 'プロフィール画像', changeImage: '画像を変更', imageFormats: 'JPG, PNG形式、最大2MB', basicInfo: '基本情報', firstName: '名', lastName: '姓', displayName: '表示名（ペンネーム）', displayNameHelp: '他のユーザーに表示される名前', bio: '自己紹介', bioPlaceholder: '簡単な自己紹介...', preferredLang: '優先言語', saveChanges: '変更を保存' }, security: { email: 'メールアドレス', verified: '確認済み', notVerified: '未確認', change: '変更する', backupCodes: 'バックアップコード', codesRemaining: '個のコード', storeSecurely: '安全な場所に保管', regenerate: '再生成', securityQuestions: 'セキュリティ質問', questionsDesc: 'アカウント復旧用の質問', changeQuestions: '質問を変更', loginHistory: 'ログイン履歴', question: '質問', question1: '子供の頃のペットの名前は？', question2: '初めて買った本のタイトルは？', question3: '一番好きな映画は？' }, notificationSettings: { emailNotifications: 'メール通知', workUpdates: '作品の更新通知', workUpdatesDesc: 'フォロー作品が更新されたとき', comments: 'コメント通知', commentsDesc: '作品にコメントがあったとき', sales: '売上通知', salesDesc: '作品が購入されたとき', translationComplete: '翻訳完了通知', translationDesc: '翻訳が完了したとき', marketing: 'マーケティングメール', marketingDesc: '新機能やキャンペーン', saveSettings: '設定を保存' }, purchases: { title: '購入履歴', desc: '過去の購入と領収書', loading: '読み込み中...', noHistory: '購入履歴がありません', receipt: '領収書', locations: { tokyo: '東京', osaka: '大阪', japan: '日本' }, paymentMethods: { creditCard: 'クレジットカード', paypal: 'PayPal', bankTransfer: '銀行振込' } }, danger: { title: '危険なアクション', warning: '以下の操作は取り消せません。', deleteAccount: 'アカウントを削除', deleteDesc: 'すべてのデータが削除されます', delete: '削除する', dataRequest: '個人データの削除リクエスト', dataRequestDesc: 'GDPRおよびプライバシー法に基づき、個人データの削除をリクエストできます。アカウントは維持されますが、個人情報は削除されます。', requestDataDeletion: '個人データの削除をリクエスト', requestDataDesc: '名前、連絡先情報、利用履歴などの個人データが削除されます。30日以内に処理されます。', requestDelete: 'リクエスト' }, modals: { changeEmail: 'メールアドレスの変更', securityRequired: 'セキュリティ質問に回答してください。', newEmail: '新しいメールアドレス', cancel: 'キャンセル', deleteConfirm: '削除の確認', deleteWarning: '警告: この操作は取り消せません！', deleteList1: '投稿した作品', deleteList2: '購入履歴', deleteList3: '収益と支払い履歴', deleteList4: '翻訳依頼', deleteList5: 'すべてのアカウント情報', typeConfirm: '確認のため「アカウントを削除」と入力：', confirmText: 'アカウントを削除する', permanentDelete: '完全に削除', newBackupCodes: '新しいバックアップコード', codesOnce: 'これらのコードは一度だけ表示されます。', copyCode: 'コードをコピー', saved: '保存しました', dataDeleteTitle: '個人データ削除リクエスト', dataDeleteInfo: 'このリクエストはGDPRおよびプライバシー法に基づく権利です。', dataDeleteExplain: '以下の個人データが削除されます：', dataItem1: '氏名、住所、連絡先情報', dataItem2: '閲覧履歴、検索履歴', dataItem3: 'Cookie関連データ', dataItem4: '分析・トラッキングデータ', dataDeleteNote: '注：アカウント、購入した作品、投稿したコンテンツは維持されます。完全削除が必要な場合は「アカウント削除」をご利用ください。', dataDeleteReason: '削除理由（任意）', selectReason: '選択してください', reasonNotNeeded: 'サービスを利用しなくなった', reasonPrivacy: 'プライバシーの懸念', reasonAccuracy: 'データの正確性に問題', reasonOther: 'その他', submitRequest: 'リクエストを送信' }, demo: { banner: 'デモモード: ダミーデータで表示', notSaved: 'デモモードでは保存されません' }, loginRequired: { title: 'ログインが必要です', message: 'アカウント設定を見るにはログインしてください', login: 'ログイン' } },
        reader: { toolbar: { backToDashboard: 'ダッシュボード', search: '検索', bookmarks: 'ブックマーク', addBookmark: 'ブックマーク追加', settings: '設定', previous: '前へ', next: '次へ' }, settings: { textSize: '文字サイズ', small: '小', medium: '中', large: '大', xlarge: '特大', theme: 'テーマ', light: 'ライト', dark: 'ダーク', sepia: 'セピア', direction: '表示方向', horizontal: '横書き', vertical: '縦書き', rtl: 'RTL' }, search: { placeholder: '検索...', noResults: '結果がありません', foundMatches: '{count}件見つかりました' }, bookmarks: { title: 'ブックマーク', noBookmarks: 'ブックマークがありません', page: 'ページ' }, highlight: { yellow: '黄色', green: '緑', blue: '青', pink: 'ピンク', remove: '削除', reportIssue: '翻訳問題を報告', selectText: '報告するテキストを選択' }, notes: { title: 'メモ', addPlaceholder: 'メモを追加...', noNotes: 'エクスポートするメモがありません', exportTxt: 'TXT', exportWord: 'Word', exportJson: 'JSON', page: 'ページ', exported: 'エクスポート' }, touchHint: '左右スワイプでページ移動', cannotHighlight: '要素をまたいでハイライトできません' },
        mangaViewer: { pageTitle: 'マンガビューワー - Publisher', fullscreen: 'フルスクリーン', pages: 'ページ一覧', close: '閉じる', loadingPage: 'ページを読み込み中...', loadFailed: 'ページの読み込みに失敗しました。', retry: '再試行', leftToRight: '左から右', rightToLeft: '右から左', vertical: '縦読み', verticalComingSoon: '縦スクロールモード（Webtoonスタイル）- 近日公開！', pageOf: '/', chapter: '章', by: '作者' },
        mangaTranslator: { pageTitle: 'マンガ翻訳エディタ - Publisher', dashboard: 'ダッシュボード', editorTitle: 'エディタ', zoomOut: '縮小', zoomIn: '拡大', uploadImage: 'クリックして画像をアップロード', uploadSupported: 'PNG, JPEG対応', toolsTitle: 'ツール', howToUse: '使い方', step1: '漫画ページをアップロード', step2: '「消去」を選択してテキストをドラッグ', step3: '「テキスト追加」を選択してクリック', step4: '翻訳テキストを入力', step5: '画像を保存', drawingTools: '描画ツール', erase: '消去（白）', addText: 'テキスト追加', select: '選択', eraserSize: '消しゴムサイズ', textOptions: 'テキスト設定', font: 'フォント', size: 'サイズ', textColor: '文字色', background: '背景', none: 'なし', textBoxes: 'テキストボックス', noTextBoxes: 'テキストボックスなし', aiTranslation: 'AI翻訳', originalText: '元のテキスト', translatedText: '翻訳結果', translate: '翻訳', applyToSelected: '選択に適用', undo: '元に戻す', clear: 'クリア', save: '保存', enterText: 'テキストを入力', clearConfirm: 'すべての変更を消去しますか？', uploadFirst: '先に画像をアップロードしてください', selectTextBoxFirst: '先にテキストボックスを選択してください', noTranslatedText: '翻訳テキストがありません', enterTextToTranslate: '翻訳するテキストを入力してください' },
        registerTranslator: { pageTitle: '翻訳者登録 - Publisher', title: '翻訳者登録', subtitle: '文化をつなぎ、世界中の読者とつながる', personalInfo: '個人情報', firstName: '名 *', lastName: '姓 *', email: 'メールアドレス *', country: '国 *', selectCountry: '国を選択', countries: { us: 'アメリカ', gb: 'イギリス', jp: '日本', de: 'ドイツ', fr: 'フランス', es: 'スペイン', cn: '中国', other: 'その他' }, languageExpertise: '言語スキル', nativeLanguage: '母国語 *', selectNativeLanguage: '母国語を選択', languages: { en: '英語', es: 'スペイン語', de: 'ドイツ語', fr: 'フランス語', ja: '日本語', zh: '中国語' }, translateFrom: '翻訳元言語 *', translateTo: '翻訳先言語 *', experienceExpertise: '経験と専門性', yearsExperience: '翻訳経験年数 *', selectExperience: '経験レベルを選択', experience: { years02: '0-2年', years35: '3-5年', years610: '6-10年', years10plus: '10年以上' }, specializations: '専門分野 *', specs: { literary: '文学小説', technical: '技術文書', manga: 'マンガ/コミック', poetry: '詩', academic: '学術文書', business: 'ビジネス文書', marketing: 'マーケティング' }, selectMultipleHint: 'Ctrl（Macはcmd）を押しながら複数選択', certifications: '資格（任意）', certificationsPlaceholder: '関連する資格や認定を記入...', portfolio: 'ポートフォリオ/ウェブサイト（任意）', agreeToTerms: '同意します：', termsOfService: '利用規約', and: 'および', revenueSharing: '収益分配契約', createAccount: '翻訳者アカウントを作成' },
        registerEditor: { pageTitle: '編集者登録 - Publisher', title: '編集者登録', subtitle: '素晴らしい物語を完璧に仕上げる', personalInfo: '個人情報', firstName: '名 *', lastName: '姓 *', email: 'メールアドレス *', country: '国 *', selectCountry: '国を選択', countries: { us: 'アメリカ', gb: 'イギリス', jp: '日本', de: 'ドイツ', fr: 'フランス', es: 'スペイン', cn: '中国', other: 'その他' }, languageProficiency: '言語能力', languagesCanEdit: '編集可能な言語 *', languages: { en: '英語', es: 'スペイン語', de: 'ドイツ語', fr: 'フランス語', ja: '日本語', zh: '中国語' }, editingExpertise: '編集専門性', typeOfEditing: '編集タイプ *', editingTypes: { developmental: '構成編集（構造、プロット、キャラクター開発）', copy: 'コピー編集（文法、スタイル、一貫性）', proof: '校正（スペル、句読点、書式）', line: 'ライン編集（文構造、語彙選択）' }, yearsExperience: '編集経験年数 *', selectExperience: '経験レベルを選択', experience: { years02: '0-2年', years35: '3-5年', years610: '6-10年', years10plus: '10年以上' }, genreExpertise: 'ジャンル専門 *', genres: { fiction: 'フィクション', nonfiction: 'ノンフィクション', manga: 'マンガ/コミック', poetry: '詩', scifi: 'SF', fantasy: 'ファンタジー', romance: 'ロマンス', mystery: 'ミステリー/スリラー', horror: 'ホラー', academic: '学術', technical: '技術' }, selectMultipleHint: 'Ctrl（Macはcmd）を押しながら複数選択', qualifications: '資格・学歴（任意）', qualificationsPlaceholder: '学位、資格、専門会員資格...', portfolio: 'ポートフォリオ/ウェブサイト（任意）', styleGuides: '熟知しているスタイルガイド', styles: { chicago: 'シカゴ・マニュアル・オブ・スタイル', ap: 'APスタイルブック', mla: 'MLAスタイル', apa: 'APAスタイル' }, agreeToTerms: '同意します：', termsOfService: '利用規約', and: 'および', revenueSharing: '収益分配契約', createAccount: '編集者アカウントを作成' },
        registerAuthor: { pageTitle: '著者登録 - Publisher', title: '著者登録', subtitle: 'あなたの物語を世界と共有しましょう', personalInfo: '個人情報', firstName: '名 *', lastName: '姓 *', penName: 'ペンネーム（任意）', penNameHint: '読者に表示される名前', email: 'メールアドレス *', country: '国 *', selectCountry: '国を選択', countries: { us: 'アメリカ', gb: 'イギリス', jp: '日本', de: 'ドイツ', fr: 'フランス', es: 'スペイン', cn: '中国', other: 'その他' }, authorDetails: '著者情報', primaryLanguage: '主な執筆言語 *', selectLanguage: '言語を選択', languages: { en: '英語', es: 'スペイン語', de: 'ドイツ語', fr: 'フランス語', ja: '日本語', zh: '中国語' }, writingGenres: '執筆ジャンル *', genres: { fiction: 'フィクション', nonfiction: 'ノンフィクション', manga: 'マンガ/コミック', poetry: '詩', scifi: 'SF', fantasy: 'ファンタジー', romance: 'ロマンス', mystery: 'ミステリー/スリラー', horror: 'ホラー', biography: '伝記/回顧録' }, genresHint: 'Ctrl（Macはcmd）を押しながら複数選択', authorBio: '著者紹介（任意）', bioPlaceholder: 'あなた自身について読者に伝えてください...', additionalServices: '追加サービス', canWorkTranslator: '翻訳者としても活動できます', canWorkEditor: '編集者としても活動できます', translationLanguages: '翻訳言語', agreeToTerms: '同意します：', termsOfService: '利用規約', and: 'および', revenueSharing: '収益分配契約', createAccount: '著者アカウントを作成' },
        support: {
            faq: { pageTitle: 'FAQ - Publisher', title: 'FAQ', heroTitle: 'よくある質問', heroSubtitle: 'Publisherに関するよくある質問への回答', searchPlaceholder: '回答を検索...', searchResults: '検索結果', clear: 'クリア', browseByCategory: 'カテゴリで探す', allQuestions: 'すべての質問', allCategories: 'すべてのカテゴリ', questions: '件の質問', noQuestions: 'このカテゴリには質問がありません', noResults: '検索結果が見つかりません：', wasHelpful: 'この回答は役に立ちましたか？', yes: 'はい', no: 'いいえ', thanksFeedback: 'フィードバックありがとうございます！', notResolved: 'まだ疑問がありますか？', tryTroubleshoot: 'トラブルシューティングウィザードで解決策を見つけましょう', startTroubleshoot: 'トラブルシューティングを開始', loadError: 'FAQを読み込めませんでした。後でもう一度お試しください。' },
            troubleshoot: { title: 'トラブルシューティング', heroTitle: 'トラブルシューティング', heroSubtitle: '問題を解決するお手伝いをします', startTroubleshoot: 'トラブルシューティングを開始', selectCategory: 'カテゴリを選択', describeIssue: '問題を説明してください', commonSolutions: '一般的な解決策', tryThese: 'これらの解決策を試してください：', stillNeedHelp: 'まだ助けが必要ですか？', contactSupport: 'サポートに連絡', back: '戻る', startOver: '最初からやり直す', progress: { step1: '問題を選択', step2: '詳細を選択', step3: '解決策' }, questions: { whatProblem: 'どのような問題でお困りですか？', selectClosest: '最も近いカテゴリを選択してください', tellMore: '詳しい状況を教えてください', selectBestMatch: '最も当てはまるものを選択してください' }, categories: { login: { title: 'ログインできない', desc: 'パスワード忘れ、アカウントロック' }, payment: { title: '支払いに関する問題', desc: '決済エラー、返金、領収書' }, reading: { title: '作品が読めない', desc: '閲覧エラー、ダウンロード問題' }, translation: { title: '翻訳に関する問題', desc: 'AI翻訳、翻訳者とのやり取り' }, publishing: { title: '作品の投稿ができない', desc: 'アップロードエラー、公開問題' }, account: { title: 'アカウント設定', desc: 'プロフィール変更、退会' } }, resolution: { didItHelp: 'この方法で問題は解決しましたか？', resolved: '解決しました', notResolved: '解決しません', relatedFaqs: '関連するよくある質問', stillNotResolved: '上記で解決しない場合は、もう一度「解決しません」をクリックしてください', contactUs: 'それでも解決しない場合', contactDesc: 'サポートチームがお手伝いします。', contactButton: 'お問い合わせ' }, success: { title: '問題が解決しました！', message: 'お役に立てて嬉しいです。', viewFaq: 'FAQを見る', backHome: 'ホームへ戻る' } },
            contact: { title: 'お問い合わせ', heroTitle: 'お問い合わせ', heroSubtitle: 'お気軽にご連絡ください', tryTroubleshootFirst: 'まずトラブルシューティングをお試しください', redirectDesc: '多くの問題はトラブルシューティングウィザードで解決できます。解決しない場合はお問い合わせフォームをご利用いただけます。', steps: '手順', step1: '1. トラブルシューティングウィザードで問題を選択', step2: '2. 提案された解決策を試す', step3: '3. 解決しない場合、お問い合わせリンクが表示されます', viewFaq: 'FAQを見る', whatHelp: 'どのようなお手伝いが必要ですか？', categoryAccountDesc: 'ログイン・登録', categoryPaymentDesc: '購入・返金', categoryTranslationDesc: 'AI・翻訳者による翻訳', categoryTechnicalDesc: 'バグ・エラー', categoryCopyrightDesc: 'DMCA・権利侵害', categoryOtherDesc: '一般的なお問い合わせ', wizardNotice: 'トラブルシューティングをお試しいただきありがとうございます。以下のフォームから未解決の問題についてお問い合わせください。', selectCategory: 'カテゴリを選択', enterDetails: '詳細を入力', mightHelp: 'これらが役立つかもしれません：', notHelpful: '役に立たない場合は続行', tellUsMore: '詳しく教えてください', name: 'お名前', email: 'メールアドレス', emailNote: 'こちらに返信を送信します', subject: '件名', subjectPlaceholder: '問題の簡単な説明', selectSubject: '件名を選択', message: 'メッセージ', messagePlaceholder: '問題の詳細を記述してください。エラーメッセージがあれば含めてください。', characters: '文字', orderId: '注文ID（任意）', agreePrivacy: '同意します：', send: 'リクエストを送信', sending: '送信中...', successTitle: 'リクエストを受け付けました！', ticketNumber: 'チケット番号：', successMessage: '平日2〜3営業日以内にご返信いたします。メールをご確認ください。', viewTickets: 'マイチケットを見る', selectCategoryAlert: 'カテゴリを選択してください', success: 'メッセージを送信しました！', error: '送信に失敗しました。もう一度お試しください。', subjects: { general: '一般的なお問い合わせ', technical: '技術サポート', billing: '請求に関する質問', partnership: 'パートナーシップ', feedback: 'フィードバック', other: 'その他' }, info: { title: 'サポート情報', email: 'メール', hours: '営業時間', hoursValue: '平日 9:00-18:00 (JST)', response: '返信時間', responseValue: '平日2〜3営業日以内', checkEmail: 'メールをご確認ください', checkEmailDesc: '返信はメールで送信されます。迷惑メールフォルダもご確認ください。', dmca: '著作権に関する報告', dmcaDesc: 'DMCA削除リクエストは専用フォームをご利用ください。', otherIssue: 'その他の問題？', backToTroubleshoot: 'トラブルシューティングに戻る' } },
            tickets: { title: 'サポートチケット', myTickets: 'マイチケット', newTicket: '新規チケット', createTicket: 'チケット作成', ticketId: 'チケットID', subject: '件名', status: 'ステータス', priority: '優先度', created: '作成日', updated: '更新日', noTickets: 'チケットがありません', viewDetails: '詳細を見る', reply: '返信', close: 'チケットを閉じる', reopen: '再開', statuses: { open: 'オープン', inProgress: '対応中', waiting: '待機中', resolved: '解決済み', closed: 'クローズ' }, priorities: { low: '低', medium: '中', high: '高', urgent: '緊急' }, demo: { translationQuality: '翻訳品質に関する質問', paymentChange: '支払い方法の変更', accountSettings: 'アカウント設定が保存されない', userMessage: 'こちらがお問い合わせ内容です。\nPlease provide more details.', adminMessage: 'お問い合わせありがとうございます。\n確認いたします。' } }
        },
        footer: { tagline: '多言語出版プラットフォーム', explore: '探索', authors: '著者', creators: 'クリエイター', write: '執筆', translate: '翻訳', pricing: '料金', help: 'ヘルプ', faq: 'FAQ', legal: '法的情報', terms: '利用規約', privacy: 'プライバシー', contact: 'お問い合わせ', copyright: '© 2024 Publisher. All rights reserved.' },
        notificationManager: { sale: '売上通知', saleDesc: '作品が購入されたとき', translationComplete: '翻訳完了', translationCompleteDesc: '翻訳が完了したとき', comment: 'コメント通知', commentDesc: '作品にコメントがあったとき', feedback: 'フィードバック通知', feedbackDesc: '読者からの評価と感想', ticketReply: 'サポート通知', ticketReplyDesc: 'お問い合わせへの返信があったとき', system: 'システム通知', systemDesc: 'メンテナンスや重要なお知らせ', notificationCenter: '通知センター', notificationCenterDesc: '未読通知を確認・管理', open: '開く', inAppNotifications: 'アプリ内通知', inAppNotificationsDesc: '通知センターに表示される通知', emailNotifications: 'メール通知', emailNotificationsDesc: 'メールで受け取る通知', bulkSettings: '一括設定', allInAppOn: 'アプリ内全てON', allInAppOff: 'アプリ内全てOFF', allEmailOn: 'メール全てON', allEmailOff: 'メール全てOFF', saveSettings: '設定を保存', settingsNote: '設定は保存後に反映されます。重要なシステム通知は設定に関わらず送信される場合があります。', marketing: 'マーケティングメール', marketingDesc: '新機能やキャンペーン', saved: '通知設定を保存しました', allOnMessage: 'すべての通知をONにしました', allOffMessage: 'すべての通知をOFFにしました' },
        common: { loading: '読み込み中...', save: '保存', cancel: 'キャンセル', delete: '削除', edit: '編集', submit: '送信', search: '検索', filter: 'フィルター', all: 'すべて', none: 'なし', yes: 'はい', no: 'いいえ', back: '戻る', next: '次へ', previous: '前へ', free: '無料' }
};

console.log('[ja.js] Japanese translations loaded');
