/**
 * Publisher Platform - Korean Translations
 * Language: 한국어 (ko)
 * Split from translations.js for modular loading
 */

const koTranslations = {
        nav: { home: '홈', browse: '둘러보기', genres: '장르', revenue: '수익', upload: '업로드', dashboard: '대시보드', register: '가입', login: '로그인', logout: '로그아웃', getStarted: '시작하기', author: '작가', translator: '번역가', editor: '편집자', notifications: '알림', settings: '설정', support: '지원' },
        home: { hero: { title: '전 세계의 이야기를 발견하세요', subtitle: '9개 언어로 이야기를 읽고 출판하세요.', startReading: '읽기 시작', startWriting: '쓰기 시작', availableIn: '9개 언어 지원' }, featured: { title: '주목 작품', viewAll: '모든 작품 보기' }, howItWorks: { title: '이용 방법', step1: { title: '작성 및 업로드', desc: '당신의 이야기를 만드세요.' }, step2: { title: 'AI 번역', desc: 'AI가 9개 언어로 번역합니다.' }, step3: { title: '수익 창출', desc: '최대 60%를 벌 수 있습니다.' } }, stats: { languages: '언어', works: '작품', authors: '작가', readers: '독자' }, forCreators: { title: '크리에이터를 위해', desc: '우리 커뮤니티에 참여하세요.', feature1: '무료 AI 번역', feature2: '최대 60% 수익', feature3: '글로벌 도달', feature4: '권리 보유', button: '창작 시작하기' }, revenue: { title: '수익 배분', platform: '플랫폼' }, cta: { title: '시작할 준비가 되셨나요?', subtitle: '수천 명의 크리에이터와 함께하세요.', createAccount: '무료 계정 만들기', browseWorks: '작품 둘러보기' } },
        login: { welcomeBack: '다시 오신 것을 환영합니다', subtitle: '계속하려면 로그인하세요', email: '이메일', emailPlaceholder: '이메일을 입력하세요', password: '비밀번호', passwordPlaceholder: '비밀번호를 입력하세요', rememberMe: '로그인 상태 유지', forgotPassword: '비밀번호를 잊으셨나요?', signIn: '로그인', orContinueWith: '또는 다음으로 계속', noAccount: '계정이 없으신가요?', signUpFree: '무료로 가입하기' },
        register: { title: '계정 만들기', subtitle: '전 세계 수천 명과 함께하세요', roles: { reader: '독자', readerDesc: '이야기 발견하기', author: '작가', authorDesc: '작성 및 출판하기', translator: '번역가', translatorDesc: '작품 번역하기' }, firstName: '이름', firstNamePlaceholder: '이름', lastName: '성', lastNamePlaceholder: '성', createPassword: '비밀번호 만들기', preferredLanguage: '선호 언어', agreeToTerms: '동의합니다', and: '및', createAccount: '계정 만들기', orSignUpWith: '또는 다음으로 가입', haveAccount: '이미 계정이 있으신가요?' },
        dashboard: { title: '대시보드', welcome: '다시 오신 것을 환영합니다', overview: '개요', myWorks: '내 작품', earnings: '수익', analytics: '분석', recentActivity: '최근 활동', quickActionsTitle: '빠른 작업', quickActions: { create: '만들기', newWork: '새 작품', upload: '업로드', fileUpload: '파일 업로드', manga: '만화', translator: '번역가', reader: '독자', preview: '미리보기' }, uploadNew: '새 작품 업로드', viewAll: '전체 보기', totalRevenue: '총 수익', thisMonth: '이번 달', totalViews: '총 조회수', totalWorks: '총 작품', followers: '팔로워', translations: '번역', recentTranslations: '최근 번역' },
        browse: { title: '작품 둘러보기', subtitle: '놀라운 이야기를 발견하세요', category: '카테고리', allCategories: '모든 카테고리', language: '언어', allLanguages: '모든 언어', sortBy: '정렬 기준', mostPopular: '인기순', newest: '최신순', highestRated: '평점순', priceLowHigh: '가격: 낮은순', applyFilters: '필터 적용' },
        notifications: { title: '알림 센터', subtitle: '알림 보기', settings: '알림 설정', all: '전체', unread: '읽지 않음', today: '오늘', thisWeek: '이번 주', allTypes: '모든 유형', unreadOnly: '읽지 않은 것만', markAllRead: '모두 읽음으로 표시', clearRead: '읽은 것 삭제', clearAll: '모두 삭제' },
        analytics: { title: '분석', subtitle: '성과를 추적하세요', overview: '개요', views: '조회수', revenue: '수익', followers: '팔로워', thisMonth: '이번 달', lastMonth: '지난 달', growth: '성장', topWorks: '인기 작품', byViews: '조회수순', byRevenue: '수익순', period: '기간', days7: '7일', days30: '30일', days90: '90일', lastUpdate: '마지막 업데이트', readingTime: '읽기 시간', engagement: '참여도', likes: '좋아요', comments: '댓글', bookmarks: '북마크', downloads: '다운로드', workTitle: '제목', readers: '독자', noData: '데이터 없음', loadFailed: '로드 실패', trend: '트렌드' },
        upload: { title: '작품 업로드', subtitle: '당신의 창작물을 세계와 공유하세요', dragDrop: '파일을 여기에 드래그 앤 드롭하세요', or: '또는', browseFiles: '파일 찾아보기', supportedFormats: '지원 형식', workTitle: '작품 제목', description: '설명', category: '카테고리', language: '언어', pricing: '가격 설정', publishNow: '지금 출판', saveDraft: '임시 저장' },
        checkout: { title: '결제', orderSummary: '주문 요약', subtotal: '소계', tax: '세금', total: '합계', paymentMethod: '결제 방법', creditCard: '신용카드', paypal: 'PayPal', completeOrder: '주문 완료', securePayment: '안전한 결제', yourOrder: '주문 내역', paySecurely: 'PayPal로 안전하게 결제', encryptedSecure: '결제 정보는 암호화되어 안전하게 보호됩니다.', revenueDistribution: '수익 배분:', author: '작가', translator: '번역가', editor: '편집자', agreeTerms: '구매 시 다음에 동의합니다' },
        payment: { successTitle: '결제 완료', cancelTitle: '결제 취소', success: '결제가 완료되었습니다!', cancelled: '결제가 취소되었습니다', thankYou: '구매해 주셔서 감사합니다.', noCharge: '요금이 청구되지 않았습니다.', orderDetails: '주문 상세', orderId: '주문 ID:', item: '항목:', amountPaid: '결제 금액:', date: '날짜:', supportingCreators: '크리에이터 지원:', revenueInfo: '귀하의 구매는 작가(40%), 번역가(20%), 편집자(10%)를 직접 지원합니다.', startReading: '읽기 시작', backToHome: '홈으로 돌아가기', receiptSent: '영수증이 이메일로 전송되었습니다', possibleReasons: '가능한 이유:', reason1: '뒤로 버튼을 클릭함', reason2: '세션 시간 초과', reason3: '결제 방법에 문제', needHelp: '도움이 필요하신가요?', contactSupport: '지원팀에 문의', tryAgain: '다시 시도', secureInfo: '안전한 결제' },
        translation: { pageTitle: '번역 상태', title: '번역 상태', backToDashboard: '대시보드로 돌아가기', original: '원문', totalTranslations: '총 번역', completed: '완료', inProgress: '진행 중', overallProgress: '전체 진행률', targetLanguage: '대상 언어', progress: '진행률', statusCompleted: '완료', translating: '번역 중...', processing: '처리 중', queued: '대기 중', waiting: '대기 중', view: '보기', aiTranslation: 'AI 번역', completed2HoursAgo: '2시간 전 완료', estRemaining: '약 3분 남음', scheduledSoon: '곧 예정', reviewed: '검토됨', professionalReview: '전문 검토', options: '번역 옵션', addLanguages: '언어 추가', requestReview: '전문 검토 요청' },
        accountSettings: { title: '계정 설정', subtitle: '프로필, 보안, 알림 등을 관리하세요', tabs: { profile: '프로필', security: '보안', notifications: '알림', purchases: '구매 내역', danger: '계정 삭제' }, profile: { image: '프로필 이미지', changeImage: '이미지 변경', imageFormats: 'JPG, PNG 형식, 최대 2MB', basicInfo: '기본 정보', firstName: '이름', lastName: '성', displayName: '표시 이름 (필명)', displayNameHelp: '다른 사용자에게 표시되는 이름', bio: '자기소개', bioPlaceholder: '간단한 자기소개를 작성하세요...', preferredLang: '선호 언어', saveChanges: '변경 사항 저장' }, security: { email: '이메일 주소', verified: '인증됨', notVerified: '미인증', change: '변경', backupCodes: '백업 코드', codesRemaining: '개 코드 남음', storeSecurely: '안전하게 보관하세요', regenerate: '재생성', securityQuestions: '보안 질문', questionsDesc: '계정 복구를 위한 질문과 답변', changeQuestions: '질문 변경', loginHistory: '로그인 기록', question: '질문', question1: '어린 시절 애완동물의 이름은?', question2: '처음 구입한 책의 제목은?', question3: '가장 좋아하는 영화는?' }, notificationSettings: { emailNotifications: '이메일 알림', workUpdates: '작품 업데이트', workUpdatesDesc: '팔로우하는 작품이 업데이트될 때', comments: '댓글 알림', commentsDesc: '작품에 댓글이 달릴 때', sales: '판매 알림', salesDesc: '작품이 구매될 때', translationComplete: '번역 완료', translationDesc: '요청한 번역이 완료될 때', marketing: '마케팅 이메일', marketingDesc: '기능 및 캠페인 소식', saveSettings: '설정 저장' }, purchases: { title: '구매 내역', desc: '과거 구매 및 영수증 다운로드', loading: '로딩 중...', noHistory: '구매 내역이 없습니다', receipt: '영수증', locations: { tokyo: '도쿄', osaka: '오사카', japan: '일본' }, paymentMethods: { creditCard: '신용카드', paypal: 'PayPal', bankTransfer: '은행 송금' } }, danger: { title: '위험 구역', warning: '다음 작업은 취소할 수 없습니다.', deleteAccount: '계정 삭제', deleteDesc: '모든 데이터가 영구적으로 삭제됩니다', delete: '삭제', dataRequest: '개인정보 삭제 요청', dataRequestDesc: 'GDPR 및 개인정보 보호법에 따라 개인정보 삭제를 요청할 수 있습니다. 계정은 유지되지만 개인정보는 삭제됩니다.', requestDataDeletion: '개인정보 삭제 요청', requestDataDesc: '이름, 연락처 정보, 이용 기록 등의 개인정보가 삭제됩니다. 30일 이내 처리됩니다.', requestDelete: '요청' }, modals: { changeEmail: '이메일 주소 변경', securityRequired: '보안 질문에 정확히 답해주세요.', newEmail: '새 이메일 주소', cancel: '취소', deleteConfirm: '계정 삭제 확인', deleteWarning: '경고: 이 작업은 취소할 수 없습니다!', deleteList1: '게시한 작품', deleteList2: '구매 내역', deleteList3: '수익 및 결제 기록', deleteList4: '번역 요청', deleteList5: '모든 계정 정보', typeConfirm: '확인을 위해 "내 계정 삭제"를 입력하세요:', confirmText: '내 계정 삭제', permanentDelete: '영구 삭제', newBackupCodes: '새 백업 코드', codesOnce: '이 코드는 한 번만 표시됩니다.', copyCode: '코드 복사', saved: '저장됨', dataDeleteTitle: '개인정보 삭제 요청', dataDeleteInfo: '이 요청은 GDPR 및 개인정보 보호법에 의해 부여된 권리입니다.', dataDeleteExplain: '다음 개인정보가 삭제됩니다:', dataItem1: '이름, 주소, 연락처 정보', dataItem2: '검색 기록, 브라우징 기록', dataItem3: '쿠키 관련 데이터', dataItem4: '분석 및 추적 데이터', dataDeleteNote: '참고: 계정, 구매한 작품, 게시한 콘텐츠는 유지됩니다. 완전 삭제를 원하시면 "계정 삭제"를 이용하세요.', dataDeleteReason: '삭제 이유 (선택)', selectReason: '선택해주세요', reasonNotNeeded: '더 이상 서비스를 이용하지 않습니다', reasonPrivacy: '개인정보 보호 우려', reasonAccuracy: '데이터 정확성 문제', reasonOther: '기타', submitRequest: '요청 제출' }, demo: { banner: '데모 모드: 테스트 데이터로 표시 중입니다.', notSaved: '데모 모드에서는 저장되지 않습니다' }, loginRequired: { title: '로그인 필요', message: '계정 설정을 보려면 로그인하세요', login: '로그인' } },
        reader: { toolbar: { backToDashboard: '대시보드', search: '검색', bookmarks: '북마크', addBookmark: '북마크 추가', settings: '설정', previous: '이전', next: '다음' }, settings: { textSize: '글자 크기', small: '소', medium: '중', large: '대', xlarge: '특대', theme: '테마', light: '라이트', dark: '다크', sepia: '세피아', direction: '방향', horizontal: '가로', vertical: '세로', rtl: 'RTL' }, search: { placeholder: '검색...', noResults: '결과 없음', foundMatches: '{count}개 일치' }, bookmarks: { title: '북마크', noBookmarks: '북마크가 없습니다', page: '페이지' }, highlight: { yellow: '노랑', green: '초록', blue: '파랑', pink: '분홍', remove: '제거', reportIssue: '번역 문제 신고', selectText: '신고할 텍스트를 선택하세요' }, notes: { title: '노트', addPlaceholder: '노트 추가...', noNotes: '내보낼 노트가 없습니다', exportTxt: 'TXT', exportWord: 'Word', exportJson: 'JSON', page: '페이지', exported: '내보내기 완료' }, touchHint: '좌우로 스와이프하여 페이지 넘기기', cannotHighlight: '요소 간에 하이라이트할 수 없습니다' },
        mangaViewer: { pageTitle: '만화 뷰어 - Publisher', fullscreen: '전체 화면', pages: '페이지', close: '닫기', loadingPage: '페이지 로딩 중...', loadFailed: '페이지 로드에 실패했습니다.', retry: '다시 시도', leftToRight: '왼쪽에서 오른쪽', rightToLeft: '오른쪽에서 왼쪽', vertical: '세로', verticalComingSoon: '세로 스크롤 모드 (웹툰 스타일) - 곧 출시!', pageOf: '/', chapter: '챕터', by: '작가' },
        mangaTranslator: { pageTitle: '만화 번역기 - Publisher', dashboard: '대시보드', editorTitle: '에디터', zoomOut: '축소', zoomIn: '확대', uploadImage: '이미지를 업로드하려면 클릭하세요', uploadSupported: 'PNG, JPEG 지원', toolsTitle: '도구', howToUse: '사용 방법', step1: '만화 페이지를 업로드하세요', step2: '"지우기"를 선택하고 텍스트 위로 드래그하세요', step3: '"텍스트 추가"를 선택하고 클릭하세요', step4: '번역된 텍스트를 입력하세요', step5: '이미지를 저장하세요', drawingTools: '그리기 도구', erase: '지우기 (흰색)', addText: '텍스트 추가', select: '선택', eraserSize: '지우개 크기', textOptions: '텍스트 옵션', font: '글꼴', size: '크기', textColor: '텍스트 색상', background: '배경', none: '없음', textBoxes: '텍스트 상자', noTextBoxes: '텍스트 상자 없음', aiTranslation: 'AI 번역', originalText: '원본 텍스트', translatedText: '번역된 텍스트', translate: '번역', applyToSelected: '선택에 적용', undo: '실행 취소', clear: '지우기', save: '저장', enterText: '텍스트 입력', clearConfirm: '모든 변경 사항을 지우시겠습니까?', uploadFirst: '먼저 이미지를 업로드하세요', selectTextBoxFirst: '먼저 텍스트 상자를 선택하세요', noTranslatedText: '번역된 텍스트가 없습니다', enterTextToTranslate: '번역할 텍스트를 입력하세요' },
        registerTranslator: { pageTitle: '번역가 등록 - Publisher', title: '번역가 등록', subtitle: '문화와 전 세계 독자를 연결하세요', personalInfo: '개인 정보', firstName: '이름 *', lastName: '성 *', email: '이메일 *', country: '국가 *', selectCountry: '국가를 선택하세요', countries: { us: '미국', gb: '영국', jp: '일본', de: '독일', fr: '프랑스', es: '스페인', cn: '중국', other: '기타' }, languageExpertise: '언어 전문성', nativeLanguage: '모국어 *', selectNativeLanguage: '모국어를 선택하세요', languages: { en: '영어', es: '스페인어', de: '독일어', fr: '프랑스어', ja: '일본어', zh: '중국어' }, translateFrom: '번역 가능 원어 *', translateTo: '번역 가능 대상 언어 *', experienceExpertise: '경험 및 전문 분야', yearsExperience: '번역 경력 *', selectExperience: '경험 수준을 선택하세요', experience: { years02: '0-2년', years35: '3-5년', years610: '6-10년', years10plus: '10년 이상' }, specializations: '전문 분야 *', specs: { literary: '문학 소설', technical: '기술 문서', manga: '만화/코믹스', poetry: '시', academic: '학술 텍스트', business: '비즈니스 문서', marketing: '마케팅 콘텐츠' }, selectMultipleHint: 'Ctrl (Mac에서는 Cmd)을 누른 채 여러 개 선택', certifications: '자격증 (선택)', certificationsPlaceholder: '관련 자격증 또는 자격을 나열하세요...', portfolio: '포트폴리오/웹사이트 (선택)', agreeToTerms: '동의합니다', termsOfService: '이용약관', and: '및', revenueSharing: '수익 분배 계약', createAccount: '번역가 계정 만들기' },
        registerEditor: { pageTitle: '편집자 등록 - Publisher', title: '편집자 등록', subtitle: '훌륭한 이야기를 완벽하게 다듬어주세요', personalInfo: '개인 정보', firstName: '이름 *', lastName: '성 *', email: '이메일 *', country: '국가 *', selectCountry: '국가를 선택하세요', countries: { us: '미국', gb: '영국', jp: '일본', de: '독일', fr: '프랑스', es: '스페인', cn: '중국', other: '기타' }, languageProficiency: '언어 능력', languagesCanEdit: '편집 가능 언어 *', languages: { en: '영어', es: '스페인어', de: '독일어', fr: '프랑스어', ja: '일본어', zh: '중국어' }, editingExpertise: '편집 전문성', typeOfEditing: '편집 유형 *', editingTypes: { developmental: '발전 편집 (구조, 플롯, 캐릭터 개발)', copy: '카피 편집 (문법, 스타일, 일관성)', proof: '교정 (맞춤법, 구두점, 형식)', line: '라인 편집 (문장 구조, 어휘 선택)' }, yearsExperience: '편집 경력 *', selectExperience: '경험 수준을 선택하세요', experience: { years02: '0-2년', years35: '3-5년', years610: '6-10년', years10plus: '10년 이상' }, genreExpertise: '장르 전문 분야 *', genres: { fiction: '소설', nonfiction: '논픽션', manga: '만화/코믹스', poetry: '시', scifi: 'SF', fantasy: '판타지', romance: '로맨스', mystery: '미스터리/스릴러', horror: '호러', academic: '학술', technical: '기술' }, selectMultipleHint: 'Ctrl (Mac에서는 Cmd)을 누른 채 여러 개 선택', qualifications: '자격 및 학력 (선택)', qualificationsPlaceholder: '학위, 자격증, 전문 회원 자격...', portfolio: '포트폴리오/웹사이트 (선택)', styleGuides: '숙지한 스타일 가이드', styles: { chicago: '시카고 매뉴얼', ap: 'AP 스타일북', mla: 'MLA 스타일', apa: 'APA 스타일' }, agreeToTerms: '동의합니다', termsOfService: '이용약관', and: '및', revenueSharing: '수익 분배 계약', createAccount: '편집자 계정 만들기' },
        registerAuthor: { pageTitle: '작가 등록 - Publisher', title: '작가 등록', subtitle: '당신의 이야기를 세계와 공유하세요', personalInfo: '개인 정보', firstName: '이름 *', lastName: '성 *', penName: '필명 (선택)', penNameHint: '독자들이 볼 이름', email: '이메일 *', country: '국가 *', selectCountry: '국가를 선택하세요', countries: { us: '미국', gb: '영국', jp: '일본', de: '독일', fr: '프랑스', es: '스페인', cn: '중국', other: '기타' }, authorDetails: '작가 정보', primaryLanguage: '주 집필 언어 *', selectLanguage: '언어를 선택하세요', languages: { en: '영어', es: '스페인어', de: '독일어', fr: '프랑스어', ja: '일본어', zh: '중국어' }, writingGenres: '집필 장르 *', genres: { fiction: '소설', nonfiction: '논픽션', manga: '만화/코믹스', poetry: '시', scifi: 'SF', fantasy: '판타지', romance: '로맨스', mystery: '미스터리/스릴러', horror: '호러', biography: '전기/회고록' }, genresHint: 'Ctrl (Mac에서는 Cmd)을 누른 채 여러 개 선택', authorBio: '작가 소개 (선택)', bioPlaceholder: '독자들에게 자신에 대해 알려주세요...', additionalServices: '추가 서비스', canWorkTranslator: '번역가로도 활동할 수 있습니다', canWorkEditor: '편집자로도 활동할 수 있습니다', translationLanguages: '번역 언어', agreeToTerms: '동의합니다', termsOfService: '이용약관', and: '및', revenueSharing: '수익 분배 계약', createAccount: '작가 계정 만들기' },
        support: {
            faq: { pageTitle: 'FAQ - Publisher', title: 'FAQ', heroTitle: '자주 묻는 질문', heroSubtitle: 'Publisher에 대한 일반적인 질문에 대한 답변을 찾아보세요', searchPlaceholder: '답변 검색...', searchResults: '검색 결과', clear: '지우기', browseByCategory: '카테고리별 검색', allQuestions: '모든 질문', allCategories: '모든 카테고리', questions: '개 질문', noQuestions: '이 카테고리에 질문이 없습니다', noResults: '검색 결과가 없습니다', wasHelpful: '이 답변이 도움이 되었나요?', yes: '예', no: '아니오', thanksFeedback: '피드백 감사합니다!', notResolved: '아직 질문이 있으신가요?', tryTroubleshoot: '우리의 어시스턴트로 해결책을 찾아보세요', startTroubleshoot: '문제 해결 시작', loadError: 'FAQ를 로드할 수 없습니다. 나중에 다시 시도하세요.' },
            troubleshoot: { title: '문제 해결', heroTitle: '문제 해결', heroSubtitle: '문제를 해결하도록 도와드리겠습니다', selectCategory: '카테고리 선택', describeIssue: '문제를 설명하세요', commonSolutions: '일반적인 해결책', tryThese: '다음 해결책을 시도해보세요:', stillNeedHelp: '아직 도움이 필요하신가요?', contactSupport: '지원팀에 문의', back: '뒤로', startOver: '처음부터 시작', progress: { step1: '문제 선택', step2: '세부 사항 선택', step3: '해결책' }, questions: { whatProblem: '어떤 문제를 겪고 계신가요?', selectClosest: '가장 가까운 카테고리를 선택하세요', tellMore: '상황에 대해 더 알려주세요', selectBestMatch: '가장 일치하는 것을 선택하세요' }, categories: { login: { title: '로그인 불가', desc: '비밀번호 분실, 계정 잠김' }, payment: { title: '결제 문제', desc: '결제 오류, 환불, 영수증' }, reading: { title: '작품 읽기 불가', desc: '표시 오류, 다운로드 문제' }, translation: { title: '번역 문제', desc: 'AI 번역, 번역가와의 소통' }, publishing: { title: '작품 업로드 불가', desc: '업로드 오류, 출판 문제' }, account: { title: '계정 설정', desc: '프로필 변경, 계정 삭제' } }, resolution: { didItHelp: '이 해결책이 도움이 되었나요?', resolved: '예, 해결됨!', notResolved: '아니오, 해결되지 않음', relatedFaqs: '관련 FAQ', stillNotResolved: '위의 내용이 도움이 되지 않았다면, 해결되지 않음을 다시 클릭하세요', contactUs: '아직 해결되지 않았나요?', contactDesc: '저희 지원팀이 도와드리겠습니다.', contactButton: '문의하기' }, success: { title: '문제가 해결되었습니다!', message: '도움이 되어 기쁩니다.', viewFaq: 'FAQ 보기', backHome: '홈으로 돌아가기' } },
            contact: { title: '문의하기', heroTitle: '연락하기', heroSubtitle: '도와드리겠습니다', name: '이름', email: '이메일', subject: '제목', selectSubject: '제목을 선택하세요', message: '메시지', messagePlaceholder: '문제나 질문을 설명하세요...', send: '메시지 보내기', sending: '전송 중...', success: '메시지가 성공적으로 전송되었습니다!', error: '전송에 실패했습니다. 다시 시도하세요.', subjects: { general: '일반 문의', technical: '기술 지원', billing: '결제 문의', partnership: '파트너십', feedback: '피드백', other: '기타' }, info: { title: '연락처 정보', email: '이메일', hours: '운영 시간', hoursValue: '월-금, 9:00-18:00 JST', response: '응답 시간', responseValue: '24시간 이내' } },
            tickets: { title: '지원 티켓', myTickets: '내 티켓', newTicket: '새 티켓', createTicket: '티켓 만들기', ticketId: '티켓 ID', subject: '제목', status: '상태', priority: '우선순위', created: '생성일', updated: '업데이트', noTickets: '티켓이 없습니다', viewDetails: '세부 정보 보기', reply: '답변', close: '티켓 닫기', reopen: '다시 열기', statuses: { open: '열림', inProgress: '진행 중', waiting: '대기 중', resolved: '해결됨', closed: '닫힘' }, priorities: { low: '낮음', medium: '중간', high: '높음', urgent: '긴급' }, demo: { translationQuality: '번역 품질에 대한 질문', paymentChange: '결제 방법 변경', accountSettings: '계정 설정이 저장되지 않음', userMessage: '여기에 제 문의 사항이 있습니다.\n자세한 내용을 알려주세요.', adminMessage: '문의해 주셔서 감사합니다.\n검토하겠습니다.' } }
        },
        footer: { tagline: '다국어 출판 플랫폼', explore: '탐색', authors: '작가', creators: '크리에이터', write: '글쓰기', translate: '번역', pricing: '가격', help: '도움말', faq: 'FAQ', legal: '법적 정보', terms: '이용약관', privacy: '개인정보', contact: '문의', copyright: '© 2024 Publisher. All rights reserved.' },
        notificationManager: { sale: '판매 알림', saleDesc: '작품이 구매되었을 때', translationComplete: '번역 완료', translationCompleteDesc: '요청한 번역이 완료되었을 때', comment: '댓글 알림', commentDesc: '작품에 댓글이 달렸을 때', feedback: '피드백 알림', feedbackDesc: '독자의 평점과 리뷰', ticketReply: '지원 알림', ticketReplyDesc: '문의에 대한 답변이 있을 때', system: '시스템 알림', systemDesc: '유지보수 및 중요 공지', notificationCenter: '알림 센터', notificationCenterDesc: '읽지 않은 알림 보기 및 관리', open: '열기', inAppNotifications: '앱 내 알림', inAppNotificationsDesc: '알림 센터에 표시되는 알림', emailNotifications: '이메일 알림', emailNotificationsDesc: '이메일로 받는 알림', bulkSettings: '일괄 설정', allInAppOn: '모든 앱 알림 ON', allInAppOff: '모든 앱 알림 OFF', allEmailOn: '모든 이메일 ON', allEmailOff: '모든 이메일 OFF', saveSettings: '설정 저장', settingsNote: '설정은 저장 후 적용됩니다. 중요한 시스템 알림은 설정에 관계없이 전송될 수 있습니다.', marketing: '마케팅 이메일', marketingDesc: '기능 및 캠페인 소식', saved: '알림 설정이 저장되었습니다', allOnMessage: '모든 알림이 활성화되었습니다', allOffMessage: '모든 알림이 비활성화되었습니다' },
        common: { loading: '로딩 중...', save: '저장', cancel: '취소', delete: '삭제', edit: '편집', submit: '제출', search: '검색', filter: '필터', all: '전체', none: '없음', yes: '예', no: '아니오', back: '뒤로', next: '다음', previous: '이전', free: '무료' }
    };

// Export for use in translation system
if (typeof module !== 'undefined' && module.exports) {
    module.exports = koTranslations;
}
