/**
 * Publisher Platform - Chinese (Simplified) Translations
 * Language: 简体中文 (zh)
 * Split from translations.js for modular loading
 */

// Initialize translations object if not exists
if (typeof window.translations === 'undefined') {
    window.translations = {};
}

window.translations.zh = {
        nav: { home: '首页', browse: '浏览', genres: '类型', revenue: '收益分配', upload: '上传作品', dashboard: '仪表板', register: '注册', login: '登录', logout: '退出', getStarted: '开始使用', author: '作者', translator: '翻译', editor: '编辑', notifications: '通知', settings: '设置', support: '支持', accountSettings: '账户设置', creatorDashboard: '创作者仪表板', library: '图书馆', translationTools: '翻译工具', mangaTranslator: '漫画翻译', translationStatus: '翻译状态', findTranslators: '查找翻译员', contact: '联系我们' },
        home: { hero: { title: '发现世界各地的故事', subtitle: '用9种语言阅读和发布', startReading: '开始阅读', startWriting: '开始写作', availableIn: '支持9种语言' }, featured: { title: '精选作品', viewAll: '查看全部' }, howItWorks: { title: '如何使用', step1: { title: '写作和上传', desc: '创作您的故事' }, step2: { title: 'AI翻译', desc: '即时翻译' }, step3: { title: '获得收益', desc: '最高60%' } }, stats: { languages: '语言', works: '作品', authors: '作者', readers: '读者' }, forCreators: { title: '为创作者', desc: '加入社区', feature1: '免费AI翻译', feature2: '60%收益', feature3: '全球触达', feature4: '保留权利', button: '开始创作' }, revenue: { title: '收益分配', platform: '平台' }, cta: { title: '准备好了吗？', subtitle: '加入创作者', createAccount: '创建免费账户', browseWorks: '浏览作品' } },
        login: { welcomeBack: '欢迎回来', subtitle: '登录继续', email: '邮箱', emailPlaceholder: '输入邮箱', password: '密码', passwordPlaceholder: '输入密码', rememberMe: '记住我', forgotPassword: '忘记密码？', signIn: '登录', orContinueWith: '或', noAccount: '没有账户？', signUpFree: '免费注册' },
        register: { title: '创建账户', subtitle: '加入全球创作者', roles: { reader: '读者', readerDesc: '发现故事', author: '作者', authorDesc: '写作发布', translator: '译者', translatorDesc: '翻译作品' }, firstName: '名', firstNamePlaceholder: '名', lastName: '姓', lastNamePlaceholder: '姓', createPassword: '创建密码', preferredLanguage: '首选语言', agreeToTerms: '我同意', and: '和', createAccount: '创建账户', orSignUpWith: '或注册', haveAccount: '已有账户？' },
        dashboard: { title: '仪表板', welcome: '欢迎回来', overview: '概览', myWorks: '我的作品', earnings: '收益', analytics: '分析', recentActivity: '最近活动', quickActions: '快捷操作', uploadNew: '上传新作品', viewAll: '查看全部', totalRevenue: '总收入', thisMonth: '本月', totalViews: '总浏览量', totalWorks: '总作品数', followers: '粉丝', translations: '翻译数', recentTranslations: '最近翻译', subtitle: '今天您作品的动态。', aiTranslation: { title: 'AI翻译', freeTier: '免费版', worksTranslated: '本月翻译作品数', freeRemaining: '剩余2次免费翻译' }, actions: { create: '创建', newWork: '新作品', upload: '上传', fileUpload: '文件上传', manga: '漫画', translator: '翻译', reader: '阅读器', preview: '预览' } },
        browse: { title: '浏览作品', subtitle: '发现精彩故事', category: '类别', allCategories: '所有类别', language: '语言', allLanguages: '所有语言', sortBy: '排序', mostPopular: '最受欢迎', newest: '最新', highestRated: '最高评分', priceLowHigh: '价格从低到高', applyFilters: '应用筛选' },
        notifications: { title: '通知中心', subtitle: '查看通知', settings: '通知设置', all: '全部', unread: '未读', today: '今天', thisWeek: '本周', allTypes: '所有类型', unreadOnly: '仅未读', markAllRead: '全部已读', clearRead: '清除已读', clearAll: '清除全部' },
        analytics: { title: '分析', subtitle: '追踪您的表现', overview: '概览', views: '浏览量', revenue: '收益', followers: '粉丝', thisMonth: '本月', lastMonth: '上月', growth: '增长', topWorks: '热门作品', byViews: '按浏览量', byRevenue: '按收益', period: '时间段', days7: '7天', days30: '30天', days90: '90天', lastUpdate: '最后更新', readingTime: '阅读时间', engagement: '互动', likes: '点赞', comments: '评论', bookmarks: '收藏', downloads: '下载', workTitle: '标题', readers: '读者', noData: '暂无数据', loadFailed: '加载失败', trend: '趋势' },
        upload: { title: '上传作品', subtitle: '分享您的创作', dragDrop: '拖放文件到此处', or: '或', browseFiles: '浏览文件', supportedFormats: '支持的格式', workTitle: '作品标题', description: '描述', category: '类别', language: '语言', pricing: '定价', publishNow: '立即发布', saveDraft: '保存草稿' },
        checkout: { title: '结账', orderSummary: '订单摘要', subtotal: '小计', tax: '税费', total: '总计', paymentMethod: '支付方式', creditCard: '信用卡', paypal: 'PayPal', completeOrder: '完成订单', securePayment: '安全支付' },
        payment: { successTitle: '支付成功', cancelTitle: '支付取消', success: '支付成功！', cancelled: '支付已取消', thankYou: '感谢您的购买。', noCharge: '未产生任何费用。', orderDetails: '订单详情', orderId: '订单号:', item: '商品:', amountPaid: '支付金额:', date: '日期:', supportingCreators: '支持创作者:', revenueInfo: '您的购买支持作者(40%)、译者(20%)和编辑(10%)。', startReading: '开始阅读', backToHome: '返回首页', receiptSent: '收据已发送到邮箱', possibleReasons: '可能的原因：', reason1: '点击了返回按钮', reason2: '会话超时', reason3: '支付方式问题', needHelp: '需要帮助？', contactSupport: '联系支持', tryAgain: '重试', secureInfo: '安全支付' },
        translation: { pageTitle: '翻译状态', title: '翻译状态', backToDashboard: '返回仪表板', original: '原文', totalTranslations: '翻译总数', completed: '已完成', inProgress: '进行中', overallProgress: '总体进度', targetLanguage: '目标语言', progress: '进度', statusCompleted: '已完成', translating: '翻译中...', processing: '处理中', queued: '排队中', waiting: '等待中', view: '查看', aiTranslation: 'AI翻译', completed2HoursAgo: '2小时前完成', estRemaining: '预计剩余3分钟', scheduledSoon: '即将开始', reviewed: '已审核', professionalReview: '专业审核', options: '翻译选项', addLanguages: '添加更多语言', requestReview: '请求专业审核' },
        accountSettings: { title: '账户设置', subtitle: '管理您的个人资料、安全、通知等', tabs: { profile: '个人资料', security: '安全', notifications: '通知', purchases: '购买记录', danger: '删除账户' }, profile: { image: '头像', changeImage: '更换头像', imageFormats: 'JPG, PNG格式，最大2MB', basicInfo: '基本信息', firstName: '名', lastName: '姓', displayName: '显示名称（笔名）', displayNameHelp: '此名称将显示给其他用户', bio: '个人简介', bioPlaceholder: '写一段简短的自我介绍...', preferredLang: '首选语言', saveChanges: '保存更改' }, security: { email: '邮箱地址', verified: '已验证', notVerified: '未验证', change: '更改', backupCodes: '备用代码', codesRemaining: '个剩余代码', storeSecurely: '请妥善保管', regenerate: '重新生成', securityQuestions: '安全问题', questionsDesc: '用于账户恢复的问题', changeQuestions: '更改问题', loginHistory: '登录历史', question: '问题', question1: '你童年宠物的名字是？', question2: '你第一本购买的书的名字是？', question3: '你最喜欢的电影是？' }, notificationSettings: { emailNotifications: '邮件通知', workUpdates: '作品更新通知', workUpdatesDesc: '当关注的作品更新时', comments: '评论通知', commentsDesc: '当作品收到评论时', sales: '销售通知', salesDesc: '当作品被购买时', translationComplete: '翻译完成通知', translationDesc: '当翻译完成时', marketing: '营销邮件', marketingDesc: '功能和活动新闻', saveSettings: '保存设置' }, purchases: { title: '购买记录', desc: '下载过去的购买和收据', loading: '加载中...', noHistory: '暂无购买记录', receipt: '收据', locations: { tokyo: '东京', osaka: '大阪', japan: '日本' }, paymentMethods: { creditCard: '信用卡', paypal: 'PayPal', bankTransfer: '银行转账' } }, danger: { title: '危险区域', warning: '以下操作无法撤销。', deleteAccount: '删除账户', deleteDesc: '所有数据将被永久删除', delete: '删除', dataRequest: '个人数据删除请求', dataRequestDesc: '根据GDPR和隐私法，您可以请求删除您的个人数据。您的账户将被保留，但个人信息将被删除。', requestDataDeletion: '请求删除个人数据', requestDataDesc: '姓名、联系方式、使用记录等个人数据将被删除。将在30天内处理。', requestDelete: '请求' }, modals: { changeEmail: '更改邮箱地址', securityRequired: '请正确回答安全问题。', newEmail: '新邮箱地址', cancel: '取消', deleteConfirm: '确认删除账户', deleteWarning: '警告：此操作无法撤销！', deleteList1: '您发布的作品', deleteList2: '购买记录', deleteList3: '收益和支付记录', deleteList4: '翻译请求', deleteList5: '所有账户信息', typeConfirm: '确认删除请输入"删除我的账户"：', confirmText: '删除我的账户', permanentDelete: '永久删除', newBackupCodes: '新备用代码', codesOnce: '这些代码只显示一次。', copyCode: '复制代码', saved: '已保存', dataDeleteTitle: '个人数据删除请求', dataDeleteInfo: '此请求是GDPR和隐私法赋予的权利。', dataDeleteExplain: '以下个人数据将被删除：', dataItem1: '姓名、地址、联系方式', dataItem2: '浏览历史、搜索历史', dataItem3: 'Cookie相关数据', dataItem4: '分析和追踪数据', dataDeleteNote: '注意：您的账户、已购买的作品和发布的内容将被保留。如需完全删除，请使用"删除账户"。', dataDeleteReason: '删除原因（可选）', selectReason: '请选择', reasonNotNeeded: '不再使用该服务', reasonPrivacy: '隐私问题', reasonAccuracy: '数据准确性问题', reasonOther: '其他', submitRequest: '提交请求' }, demo: { banner: '演示模式：正在显示模拟数据。', notSaved: '演示模式下不会保存' }, loginRequired: { title: '需要登录', message: '请登录以查看账户设置', login: '登录' } },
        reader: { toolbar: { backToDashboard: '仪表板', search: '搜索', bookmarks: '书签', addBookmark: '添加书签', settings: '设置', previous: '上一页', next: '下一页' }, settings: { textSize: '字体大小', small: '小', medium: '中', large: '大', xlarge: '特大', theme: '主题', light: '浅色', dark: '深色', sepia: '护眼', direction: '方向', horizontal: '横排', vertical: '竖排', rtl: 'RTL' }, search: { placeholder: '搜索...', noResults: '未找到结果', foundMatches: '找到{count}个匹配' }, bookmarks: { title: '书签', noBookmarks: '暂无书签', page: '页' }, highlight: { yellow: '黄色', green: '绿色', blue: '蓝色', pink: '粉色', remove: '删除', reportIssue: '报告翻译问题', selectText: '请选择要报告的文本' }, notes: { title: '笔记', addPlaceholder: '添加笔记...', noNotes: '没有可导出的笔记', exportTxt: 'TXT', exportWord: 'Word', exportJson: 'JSON', page: '页', exported: '已导出' }, touchHint: '左右滑动翻页', cannotHighlight: '无法跨元素高亮' },
        mangaViewer: { pageTitle: '漫画阅读器 - Publisher', fullscreen: '全屏', pages: '页面', close: '关闭', loadingPage: '正在加载页面...', loadFailed: '页面加载失败。', retry: '重试', leftToRight: '从左到右', rightToLeft: '从右到左', vertical: '垂直', verticalComingSoon: '垂直滚动模式（条漫风格）- 即将推出！', pageOf: '/', chapter: '章节', by: '作者' },
        mangaTranslator: { pageTitle: '漫画翻译编辑器 - Publisher', dashboard: '仪表板', editorTitle: '编辑器', zoomOut: '缩小', zoomIn: '放大', uploadImage: '点击上传图片', uploadSupported: '支持PNG, JPEG', toolsTitle: '工具', howToUse: '使用方法', step1: '上传漫画页面', step2: '选择"擦除"并拖动文字', step3: '选择"添加文字"并点击', step4: '输入翻译文字', step5: '保存图片', drawingTools: '绘图工具', erase: '擦除（白色）', addText: '添加文字', select: '选择', eraserSize: '橡皮擦大小', textOptions: '文字设置', font: '字体', size: '大小', textColor: '文字颜色', background: '背景', none: '无', textBoxes: '文字框', noTextBoxes: '暂无文字框', aiTranslation: 'AI翻译', originalText: '原文', translatedText: '翻译结果', translate: '翻译', applyToSelected: '应用到选中', undo: '撤销', clear: '清除', save: '保存', enterText: '输入文字', clearConfirm: '清除所有更改？', uploadFirst: '请先上传图片', selectTextBoxFirst: '请先选择文字框', noTranslatedText: '没有翻译文字', enterTextToTranslate: '请输入要翻译的文字' },
        registerTranslator: { pageTitle: '译者注册 - Publisher', title: '译者注册', subtitle: '连接文化，沟通世界读者', personalInfo: '个人信息', firstName: '名 *', lastName: '姓 *', email: '电子邮箱 *', country: '国家 *', selectCountry: '选择您的国家', countries: { us: '美国', gb: '英国', jp: '日本', de: '德国', fr: '法国', es: '西班牙', cn: '中国', other: '其他' }, languageExpertise: '语言专长', nativeLanguage: '母语 *', selectNativeLanguage: '选择您的母语', languages: { en: '英语', es: '西班牙语', de: '德语', fr: '法语', ja: '日语', zh: '中文' }, translateFrom: '我可以翻译的源语言 *', translateTo: '我可以翻译的目标语言 *', experienceExpertise: '经验与专长', yearsExperience: '翻译经验年数 *', selectExperience: '选择经验级别', experience: { years02: '0-2年', years35: '3-5年', years610: '6-10年', years10plus: '10年以上' }, specializations: '专业领域 *', specs: { literary: '文学小说', technical: '技术写作', manga: '漫画/动漫', poetry: '诗歌', academic: '学术文献', business: '商业文档', marketing: '营销内容' }, selectMultipleHint: '按住Ctrl（Mac为Cmd）多选', certifications: '资格证书（可选）', certificationsPlaceholder: '列出相关资格或认证...', portfolio: '作品集/网站（可选）', agreeToTerms: '我同意', termsOfService: '服务条款', and: '和', revenueSharing: '收益分成协议', createAccount: '创建译者账户' },
        registerEditor: { pageTitle: '编辑注册 - Publisher', title: '编辑注册', subtitle: '帮助打磨优秀故事至完美', personalInfo: '个人信息', firstName: '名 *', lastName: '姓 *', email: '电子邮箱 *', country: '国家 *', selectCountry: '选择您的国家', countries: { us: '美国', gb: '英国', jp: '日本', de: '德国', fr: '法国', es: '西班牙', cn: '中国', other: '其他' }, languageProficiency: '语言能力', languagesCanEdit: '我可以编辑的语言 *', languages: { en: '英语', es: '西班牙语', de: '德语', fr: '法语', ja: '日语', zh: '中文' }, editingExpertise: '编辑专长', typeOfEditing: '编辑类型 *', editingTypes: { developmental: '发展编辑（结构、情节、角色发展）', copy: '文字编辑（语法、风格、一致性）', proof: '校对（拼写、标点、格式）', line: '行编辑（句子结构、词汇选择）' }, yearsExperience: '编辑经验年数 *', selectExperience: '选择经验级别', experience: { years02: '0-2年', years35: '3-5年', years610: '6-10年', years10plus: '10年以上' }, genreExpertise: '专业类型 *', genres: { fiction: '虚构', nonfiction: '非虚构', manga: '漫画/动漫', poetry: '诗歌', scifi: '科幻', fantasy: '奇幻', romance: '言情', mystery: '悬疑/惊悚', horror: '恐怖', academic: '学术', technical: '技术' }, selectMultipleHint: '按住Ctrl（Mac为Cmd）多选', qualifications: '资格与学历（可选）', qualificationsPlaceholder: '学位、证书、专业会员资格...', portfolio: '作品集/网站（可选）', styleGuides: '熟悉的风格指南', styles: { chicago: '芝加哥格式手册', ap: 'AP风格指南', mla: 'MLA格式', apa: 'APA格式' }, agreeToTerms: '我同意', termsOfService: '服务条款', and: '和', revenueSharing: '收益分成协议', createAccount: '创建编辑账户' },
        registerAuthor: { pageTitle: '作者注册 - Publisher', title: '作者注册', subtitle: '开始与世界分享您的故事', personalInfo: '个人信息', firstName: '名 *', lastName: '姓 *', penName: '笔名（可选）', penNameHint: '读者将看到的名字', email: '电子邮箱 *', country: '国家 *', selectCountry: '选择您的国家', countries: { us: '美国', gb: '英国', jp: '日本', de: '德国', fr: '法国', es: '西班牙', cn: '中国', other: '其他' }, authorDetails: '作者详情', primaryLanguage: '主要写作语言 *', selectLanguage: '选择语言', languages: { en: '英语', es: '西班牙语', de: '德语', fr: '法语', ja: '日语', zh: '中文' }, writingGenres: '写作类型 *', genres: { fiction: '虚构', nonfiction: '非虚构', manga: '漫画/动漫', poetry: '诗歌', scifi: '科幻', fantasy: '奇幻', romance: '言情', mystery: '悬疑/惊悚', horror: '恐怖', biography: '传记/回忆录' }, genresHint: '按住Ctrl（Mac为Cmd）多选', authorBio: '作者简介（可选）', bioPlaceholder: '向读者介绍您自己...', additionalServices: '附加服务', canWorkTranslator: '我也可以担任翻译', canWorkEditor: '我也可以担任编辑', translationLanguages: '翻译语言', agreeToTerms: '我同意', termsOfService: '服务条款', and: '和', revenueSharing: '收益分成协议', createAccount: '创建作者账户' },
        support: {
            faq: { pageTitle: '常见问题 - Publisher', title: '常见问题', heroTitle: '常见问题', heroSubtitle: '查找有关Publisher的常见问题的答案', searchPlaceholder: '搜索答案...', searchResults: '搜索结果', clear: '清除', browseByCategory: '按类别浏览', allQuestions: '所有问题', allCategories: '所有类别', questions: '个问题', noQuestions: '此类别中没有问题', noResults: '未找到相关结果：', wasHelpful: '这个回答有帮助吗？', yes: '是', no: '否', thanksFeedback: '感谢您的反馈！', notResolved: '还有问题吗？', tryTroubleshoot: '使用故障排除向导找到解决方案', startTroubleshoot: '开始故障排除', loadError: '无法加载常见问题。请稍后重试。' },
            troubleshoot: { title: '故障排除', heroTitle: '故障排除向导', heroSubtitle: '让我们帮助您找到解决方案', startTroubleshoot: '开始故障排除', selectCategory: '选择类别', describeIssue: '描述您的问题', commonSolutions: '常见解决方案', tryThese: '尝试这些解决方案：', stillNeedHelp: '仍需帮助？', contactSupport: '联系支持', back: '返回', startOver: '重新开始' },
            contact: { title: '联系我们', heroTitle: '联系我们', heroSubtitle: '我们随时为您提供帮助', tryTroubleshootFirst: '请先尝试故障排除', redirectDesc: '许多问题可以通过故障排除向导解决。如果向导无法解决，您可以使用联系表单。', steps: '步骤', step1: '1. 在故障排除向导中选择您的问题', step2: '2. 尝试建议的解决方案', step3: '3. 如果未解决，将显示联系链接', viewFaq: '查看常见问题', whatHelp: '我们能为您提供什么帮助？', categoryAccountDesc: '登录与注册', categoryPaymentDesc: '购买与退款', categoryTranslationDesc: 'AI与人工翻译', categoryTechnicalDesc: '错误与问题', categoryCopyrightDesc: 'DMCA与版权侵权', categoryOtherDesc: '一般咨询', wizardNotice: '感谢您尝试故障排除向导。请使用以下表单联系我们解决未解决的问题。', selectCategory: '选择类别', enterDetails: '输入详情', mightHelp: '这些可能有帮助：', notHelpful: '没有帮助？继续', tellUsMore: '请告诉我们更多', name: '您的姓名', email: '电子邮件地址', emailNote: '我们将通过此邮箱回复', subject: '主题', subjectPlaceholder: '简要描述您的问题', selectSubject: '选择主题', message: '消息', messagePlaceholder: '请详细描述您的问题。如有错误消息请一并提供。', characters: '字符', orderId: '订单ID（可选）', agreePrivacy: '我同意', send: '提交请求', sending: '提交中...', successTitle: '请求已提交！', ticketNumber: '工单号：', successMessage: '我们将在2-3个工作日内回复。请查收您的邮箱。', viewTickets: '查看我的工单', selectCategoryAlert: '请选择一个类别', success: '消息发送成功！', error: '发送失败。请重试。', subjects: { general: '一般咨询', technical: '技术支持', billing: '账单问题', partnership: '合作伙伴', feedback: '反馈', other: '其他' }, info: { title: '支持信息', email: '电子邮件', hours: '工作时间', hoursValue: '周一至周五，9:00-18:00 (JST)', response: '响应时间', responseValue: '2-3个工作日内', checkEmail: '请查收您的邮箱', checkEmailDesc: '回复将通过邮件发送。请也检查垃圾邮件文件夹。', dmca: '版权报告', dmcaDesc: 'DMCA删除请求请使用专用表单。', otherIssue: '其他问题？', backToTroubleshoot: '返回故障排除' } },
            tickets: { title: '支持工单', myTickets: '我的工单', newTicket: '新建工单', createTicket: '创建工单', ticketId: '工单ID', subject: '主题', status: '状态', priority: '优先级', created: '创建时间', updated: '更新时间', noTickets: '没有找到工单', viewDetails: '查看详情', reply: '回复', close: '关闭工单', reopen: '重新打开', statuses: { open: '开放', inProgress: '处理中', waiting: '等待中', resolved: '已解决', closed: '已关闭' }, priorities: { low: '低', medium: '中', high: '高', urgent: '紧急' }, demo: { translationQuality: '翻译质量问题', paymentChange: '更改支付方式', accountSettings: '账户设置无法保存', userMessage: '这是我的咨询内容。\n请提供更多详细信息。', adminMessage: '感谢您的咨询。\n我们会尽快处理。' } }
        },
        footer: { tagline: '多语言出版平台', explore: '探索', authors: '作者', creators: '创作者', write: '写作', translate: '翻译', pricing: '定价', help: '帮助', faq: '常见问题', legal: '法律', terms: '条款', privacy: '隐私', contact: '联系', copyright: '© 2024 Publisher. 版权所有。' },
        notificationManager: { sale: '销售通知', saleDesc: '当作品被购买时', translationComplete: '翻译完成', translationCompleteDesc: '当翻译完成时', comment: '评论通知', commentDesc: '当作品收到评论时', feedback: '反馈通知', feedbackDesc: '读者的评分和反馈', ticketReply: '支持通知', ticketReplyDesc: '当您的咨询有回复时', system: '系统通知', systemDesc: '维护和重要公告', notificationCenter: '通知中心', notificationCenterDesc: '查看和管理未读通知', open: '打开', inAppNotifications: '应用内通知', inAppNotificationsDesc: '在通知中心显示的通知', emailNotifications: '邮件通知', emailNotificationsDesc: '通过邮件接收的通知', bulkSettings: '批量设置', allInAppOn: '应用内全部开启', allInAppOff: '应用内全部关闭', allEmailOn: '邮件全部开启', allEmailOff: '邮件全部关闭', saveSettings: '保存设置', settingsNote: '设置保存后生效。重要的系统通知可能会不受设置影响而发送。', marketing: '营销邮件', marketingDesc: '功能和活动新闻', saved: '通知设置已保存', allOnMessage: '所有通知已开启', allOffMessage: '所有通知已关闭' },
        common: { loading: '加载中...', save: '保存', cancel: '取消', delete: '删除', edit: '编辑', submit: '提交', search: '搜索', filter: '筛选', all: '全部', none: '无', yes: '是', no: '否', back: '返回', next: '下一个', previous: '上一个', free: '免费' }
};

console.log('[zh.js] Chinese translations loaded');
